// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/marketing-2/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import About from './About.svelte';
	import Service from './Service.svelte';
	import Portfolio from './Portfolio.svelte';
	import Step from './Step.svelte';
	import Testimonial from './Testimonial.svelte';
	import Action from './Action.svelte';
	import Blog from './Blog.svelte';
	import Cta from './Cta.svelte';
	import Contact from './Contact.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'services',
			name: 'Services'
		},
		{
			id: 'portfolio',
			name: 'Portfolio'
		},
		{
			id: 'testimonial',
			name: 'Testimonial'
		},
		{
			id: 'blog',
			name: 'Blog'
		},
		{
			id: 'contact',
			name: 'Contact'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<section class="lg:-mt-[72px]">
	<MarqueeGroup customClass="bg-default-100 dark:bg-default-50 border-none" />
</section>

<About />

<Service />

<Portfolio />

<Step />

<Testimonial />

<Action />

<Blog />

<Cta />

<Contact />

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/marketing-2/index.vue
<template>
  <Navbar1
    menu-position="fixed"
    :navbar-link="navLinkData"
    btn-text="Download"
    :btn-icon="DownloadCloudIcon"
  />

  <Marketing2Hero />

  <section class="lg:-mt-[72px]">
    <MarqueeGroup custom-class="bg-default-100 dark:bg-default-50 border-none" />
  </section>

  <About />

  <Service />

  <Portfolio />

  <Step />

  <Testimonial />

  <Action />

  <Blog />

  <Cta />

  <Contact />

  <Footer />

  <client-only>
    <BackToTop />
  </client-only>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

import Navbar1 from '@/layouts/partials/Navbar1.vue'
import Marketing2Hero from '@/components/heros/Marketing2Hero.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import About from '@/pages/landings/marketing-2/components/About.vue'
import Service from '@/pages/landings/marketing-2/components/Service.vue'
import Portfolio from '@/pages/landings/marketing-2/components/Portfolio.vue'
import Step from '@/pages/landings/marketing-2/components/Step.vue'
import Testimonial from '@/pages/landings/marketing-2/components/Testimonial.vue'
import Action from '@/pages/landings/marketing-2/components/Action.vue'
import Blog from '@/pages/landings/marketing-2/components/Blog.vue'
import Cta from '@/pages/landings/marketing-2/components/Cta.vue'
import Contact from '@/pages/landings/marketing-2/components/Contact.vue'
import Footer from '@/layouts/partials/Footer.vue'
import BackToTop from '@/layouts/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home'
  },
  {
    id: 'about',
    name: 'About'
  },
  {
    id: 'services',
    name: 'Services'
  },
  {
    id: 'portfolio',
    name: 'Portfolio'
  },
  {
    id: 'testimonial',
    name: 'Testimonial'
  },
  {
    id: 'blog',
    name: 'Blog'
  },
  {
    id: 'contact',
    name: 'Contact'
  }
]
</script>
