// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/admin/projects/projects.component.ts
import { Component } from '@angular/core'
import { projects } from './data'
import { CommonModule } from '@angular/common'
import { BreadcrumbComponent } from '@components/breadcrumb/breadcrumb.component'

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, BreadcrumbComponent],
  template: `
    <app-breadcrumb [pageTitle]="'Projects'" />
    <section>
      <div class="container">
        <div class="my-6 space-y-6">
          <div class="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
            @for (item of project; track $index) {
              <div
                class="overflow-hidden rounded-md border border-default-200 bg-white dark:bg-default-50"
              >
                <div
                  class="flex items-center justify-between border-b border-default-200 px-4 py-3"
                >
                  <h5 class="text-lg text-default-900">{{ item.title }}</h5>
                  <div
                    class="rounded-md  px-1.5 py-1 text-xs font-medium text-white"
                    [ngClass]="{
                      'bg-teal-500':
                        item.status === 'Completed' ||
                        item.status === 'Frontend Completed',
                      'bg-amber-500': item.status === 'Pending',
                      'bg-primary': item.status === 'In Progress'
                    }"
                    role="alert"
                  >
                    <span>{{ item.status }}</span>
                  </div>
                </div>
                @for (data of item.items; track $index) {
                  <div class="flex flex-col">
                    <div class="px-6 py-3">
                      <h5 class="my-2">
                        <a
                          href="javascript:void(0);"
                          class="text-default-900"
                          >{{ data.name }}</a
                        >
                      </h5>
                      <p class="mb-9 text-sm text-default-500">
                        {{ data.description }}
                      </p>

                      <div class="flex -space-x-2">
                        @for (image of data.images; track $index) {
                          <a href="javascript: void(0);">
                            <img
                              class="inline-block size-12 rounded-full border-2 border-default-50"
                              src="{{ image }}"
                              alt="Image Description"
                            />
                          </a>
                        }
                        <a href="javascript: void(0);">
                          <div class="relative inline-flex">
                            <button
                              class="inline-flex size-12 items-center justify-center rounded-full border-2 border-white bg-default-200 align-middle text-sm font-medium text-default-700 shadow-sm transition-all hover:bg-default-300 dark:border-default-50"
                            >
                              <span class="font-medium leading-none">2+</span>
                            </button>
                          </div>
                        </a>
                      </div>
                    </div>

                    <div class="border-t border-default-200 p-5">
                      <div class="grid gap-4 lg:grid-cols-2">
                        <div class="flex items-center justify-between gap-2">
                          <a href="javascript:void(0);" class="text-sm">
                            <i class="mgc_calendar_line me-2 text-lg"></i>
                            <span class="align-text-bottom">{{
                              data.dates.calendar
                            }}</span>
                          </a>

                          <a href="javascript:void(0);" class="text-sm">
                            <i class="mgc_align_justify_line me-2 text-lg"></i>
                            <span class="align-text-bottom">{{
                              data.dates.justify
                            }}</span>
                          </a>

                          <a href="javascript:void(0);" class="text-sm">
                            <i class="mgc_comment_line me-2 text-lg"></i>
                            <span class="align-text-bottom">{{
                              data.dates.comment
                            }}</span>
                          </a>
                        </div>
                        <div class="flex items-center gap-2">
                          <div class="h-1.5 w-full rounded-full bg-default-200">
                            <div
                              class="h-1.5 w-2/3 rounded-full {{
                                data.progress.barColor
                              }}"
                            ></div>
                          </div>
                          <span>{{ data.progress.percentage }}%</span>
                        </div>
                      </div>
                    </div>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      </div>
    </section>
  `,
  styles: ``,
})
export class ProjectsComponent {
  project = projects
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Portfolio2/components/Projects.jsx
import portfolio2 from "@/assets/images/landing/portfolio-2/img-2.jpg";
import portfolio3 from "@/assets/images/landing/portfolio-2/img-3.jpg";
import portfolio4 from "@/assets/images/landing/portfolio-2/img-4.jpg";
import { LuMoveRight } from "react-icons/lu";
import { Link } from "react-router-dom";
const Projects = () => {
  return (
    <section id="project" className="py-10 lg:py-20">
      <div className="container">
        <div className="mb-10 flex items-end justify-between">
          <div className="mx-auto max-w-2xl text-center">
            <span className="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary">
              Our Project
            </span>
            <h2 className="mt-4 text-4xl font-medium capitalize text-default-950">
              Recent Endeavors
            </h2>
          </div>
        </div>
        <div className="grid grid-cols-1 items-center gap-6 md:grid-cols-2">
          <div className="group relative">
            <img src={portfolio2} className="h-full w-full rounded-xl" />
            <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
              <div className="p-6 text-center">
                <h2 className="text-3xl font-medium text-white">
                  Branding Identity
                </h2>
                <p className="mt-2 text-base text-white">Branding</p>
              </div>
            </div>
          </div>
          <div>
            <div className="group relative">
              <img src={portfolio3} className="h-full w-full rounded-xl" />
              <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
                <div className="p-6 text-center">
                  <h2 className="text-3xl font-medium text-white">
                    The Space Needle
                  </h2>
                  <p className="mt-2 text-base text-white">Branding</p>
                </div>
              </div>
            </div>
            <div className="group relative mt-5">
              <img src={portfolio4} className="h-full w-full rounded-xl" />
              <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
                <div className="p-6 text-center">
                  <h2 className="text-3xl font-medium text-white">
                    Emergency Response and Cleanup
                  </h2>
                  <p className="mt-2 text-base text-white">Branding</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-5 flex justify-center">
          <div className="inline-block">
            <Link
              to=""
              className="mt-6 flex items-center justify-center gap-2 rounded-md border border-default-300 px-6 py-2 text-base text-default-950 transition-all hover:border-primary hover:bg-primary hover:text-white"
            >
              All Project <LuMoveRight className="size-7" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Projects;
