// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/marketing3/projects.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <!-- Start About -->
    <section id="projects" class="overflow-hidden py-10">
      <div class="container">
        <div
          class="relative overflow-hidden rounded-3xl bg-white shadow-[rgba(17,_17,_26,_0.1)_0px_0px_24px] dark:bg-default-50"
        >
          <div class="grid items-center gap-6 lg:grid-cols-2">
            <div class="relative p-6 text-center">
              <span
                class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
                >Highlighted Projects</span
              >
              <h2 class="mt-4 text-3xl font-medium text-default-950">
                Innovative Design Solutions 💡
              </h2>
              <p class="mb-8 mt-5 text-base">
                Customize your design using a variety of theme options in the
                WordPress Customizer and witness instant changes.
              </p>
              <a
                href="javascript:void(0);"
                class="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-6 py-2 text-white transition-all duration-300 hover:bg-primary-700"
                >Read More
                <lucide-angular
                  name="move-right"
                  class="size-6"
                ></lucide-angular>
              </a>
            </div>
            <img
              src="assets/images/landing/marketing-3/img-2.jpg"
              class="h-full w-full"
              alt=""
            />
          </div>
        </div>
      </div>
    </section>
    <!-- End About -->
  `,
  styles: ``,
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
})
export class ProjectsComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Portfolio2/components/Projects.jsx
import portfolio2 from "@/assets/images/landing/portfolio-2/img-2.jpg";
import portfolio3 from "@/assets/images/landing/portfolio-2/img-3.jpg";
import portfolio4 from "@/assets/images/landing/portfolio-2/img-4.jpg";
import { LuMoveRight } from "react-icons/lu";
import { Link } from "react-router-dom";
const Projects = () => {
  return (
    <section id="project" className="py-10 lg:py-20">
      <div className="container">
        <div className="mb-10 flex items-end justify-between">
          <div className="mx-auto max-w-2xl text-center">
            <span className="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary">
              Our Project
            </span>
            <h2 className="mt-4 text-4xl font-medium capitalize text-default-950">
              Recent Endeavors
            </h2>
          </div>
        </div>
        <div className="grid grid-cols-1 items-center gap-6 md:grid-cols-2">
          <div className="group relative">
            <img src={portfolio2} className="h-full w-full rounded-xl" />
            <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
              <div className="p-6 text-center">
                <h2 className="text-3xl font-medium text-white">
                  Branding Identity
                </h2>
                <p className="mt-2 text-base text-white">Branding</p>
              </div>
            </div>
          </div>
          <div>
            <div className="group relative">
              <img src={portfolio3} className="h-full w-full rounded-xl" />
              <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
                <div className="p-6 text-center">
                  <h2 className="text-3xl font-medium text-white">
                    The Space Needle
                  </h2>
                  <p className="mt-2 text-base text-white">Branding</p>
                </div>
              </div>
            </div>
            <div className="group relative mt-5">
              <img src={portfolio4} className="h-full w-full rounded-xl" />
              <div className="absolute inset-x-2 bottom-2 rounded-md bg-white/10 opacity-0 backdrop-blur-xl transition-all duration-500 group-hover:opacity-100">
                <div className="p-6 text-center">
                  <h2 className="text-3xl font-medium text-white">
                    Emergency Response and Cleanup
                  </h2>
                  <p className="mt-2 text-base text-white">Branding</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-5 flex justify-center">
          <div className="inline-block">
            <Link
              to=""
              className="mt-6 flex items-center justify-center gap-2 rounded-md border border-default-300 px-6 py-2 text-base text-default-950 transition-all hover:border-primary hover:bg-primary hover:text-white"
            >
              All Project <LuMoveRight className="size-7" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Projects;
