// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Vue/Vue/src/views/landings/ebook/index.vue
<template>
  <Navbar2 :navbar-link="navLinkData" btn-text="Download" :btn-icon="DownloadCloudIcon" />

  <EbookHero />

  <About />

  <Benefits />

  <Course />

  <Testimonial />

  <Contact />

  <Footer />

  <BackToTop />
</template>

<script setup lang="ts">
import Navbar2 from '@/layout/partials/Navbar2.vue'
import EbookHero from '@/components/heros/EbookHero.vue'
import About from '@/views/landings/ebook/About.vue'
import Benefits from '@/views/landings/ebook/Benefits.vue'
import Course from '@/views/landings/ebook/Course.vue'
import Testimonial from '@/views/landings/ebook/Testimonial.vue'
import Contact from '@/views/landings/ebook/Contact.vue'
import Footer from '@/layout/partials/Footer.vue'
import BackToTop from '@/layout/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home',
  },
  {
    id: 'about',
    name: 'About',
  },
  {
    id: 'benefits',
    name: 'Benefits',
  },
  {
    id: 'courses',
    name: 'Courses',
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
  },
]
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/ebook/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar2 from '$lib/components/layouts/Navbar2.svelte';
	import Hero from './Hero.svelte';
	import About from './About.svelte';
	import Benefits from './Benefits.svelte';
	import Course from './Course.svelte';
	import Testimonial from './Testimonial.svelte';
	import Contact from './Contact.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'benefits',
			name: 'Benefits'
		},
		{
			id: 'courses',
			name: 'Courses'
		},
		{
			id: 'testimonials',
			name: 'Testimonials'
		}
	];
</script>

<Navbar2 navbarLink={navLinkData} />

<Hero />

<About />

<Benefits />

<Course />

<Testimonial />

<Contact />
