// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/startup/Blog.svelte
<script lang="ts">
	import BlogCard3 from '$lib/components/widgets/BlogCard3.svelte';
	import type { BlogType } from '$lib/types/landing';
	import { startupImg8, startupImg9 } from '$lib/utilities/images';

	const blogData: BlogType[] = [
		{
			image: startupImg8,
			title: 'Elegant Branding Work for Red Circle by Oddone',
			description: 'Oddone collaborated with brand strategist Caren Williams to create elegant branding for Red Circle, a San Francisco-based startup.'
		},
		{
			image: startupImg9,
			title: 'Random Explorations with Cinema 4D and Redshift',
			description: 'Nidia Dias, a 3D designer from Portugal, showcases her impressive portfolio in random explorations with Cinema 4D and Redshift.'
		},
	]
</script>

<section id="blog" class="py-10 lg:py-20">
	<div class="container">
		<div class="mb-10 flex items-end justify-between">
			<div class="mx-auto max-w-2xl text-center">
            <span
							class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
						>Our Blog</span>
				<h2 class="my-4 text-4xl font-medium text-default-950">
					Explore Blog
				</h2>
				<p class="text-base">
					Web development offers three primary specializations: front-end
					developer, back-end developer, and full-stack developer.
				</p>
			</div>
		</div>

		<div class="grid gap-6 xl:grid-cols-2">
			{#each blogData as blog}
				<BlogCard3 {blog} />
			{/each}
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/startup/blog.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],

  template: `
    <!-- Start Blog -->
    <section id="blog" class="py-10 lg:py-20">
      <div class="container">
        <div class="mb-10 flex items-end justify-between">
          <div class="mx-auto max-w-2xl text-center">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Our Blog</span
            >
            <h2 class="my-4 text-4xl font-medium text-default-950">
              Explore Blog
            </h2>
            <p class="text-base">
              Web development offers three primary specializations: front-end
              developer, back-end developer, and full-stack developer.
            </p>
          </div>
        </div>
        <!-- flex End -->

        <div class="grid gap-6 xl:grid-cols-2">
          <div class="rounded-md border border-default-200 p-6">
            <div class="grid items-center gap-6 sm:grid-cols-5">
              <div class="col-span-2">
                <img
                  src="assets/images/landing/startup/img-8.jpg"
                  class="my-auto h-full w-full rounded-md"
                  alt=""
                />
              </div>

              <div class="group sm:col-span-3">
                <h3 class="mb-4 text-2xl font-medium text-default-950">
                  Elegant Branding Work for Red Circle by Oddone
                </h3>
                <p class="mb-5 mt-3 text-sm">
                  Oddone collaborated with brand strategist Caren Williams to
                  create elegant branding for Red Circle, a San Francisco-based
                  startup.
                </p>
                <a
                  href="javascript:void(0);"
                  class="text-lg font-medium text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-5 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
              <!-- col-span-2 End -->
            </div>
            <!-- grid End -->
          </div>
          <!-- col End -->

          <div class="rounded-md border border-default-200 p-6">
            <div class="grid items-center gap-6 sm:grid-cols-5">
              <div class="col-span-2">
                <img
                  src="assets/images/landing/startup/img-9.jpg"
                  class="my-auto h-full w-full rounded-md"
                  alt=""
                />
              </div>

              <div class="group sm:col-span-3">
                <h3 class="mb-4 text-2xl font-medium text-default-950">
                  Random Explorations with Cinema 4D and Redshift
                </h3>
                <p class="mb-5 mt-3 text-sm">
                  Nidia Dias, a 3D designer from Portugal, showcases her
                  impressive portfolio in random explorations with Cinema 4D and
                  Redshift.
                </p>
                <a
                  href="javascript:void(0);"
                  class="text-lg font-medium text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-5 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
              <!-- col-span-2 End -->
            </div>
            <!-- grid End -->
          </div>
          <!-- col End -->
        </div>
        <!-- Grid End -->
      </div>
      <!-- container End -->
    </section>
    <!-- End Blog -->
  `,
  styles: ``,
})
export class BlogComponent {}
