// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/admin/chat/chat.component.ts
import { Component, ElementRef, ViewChild, Renderer2 } from '@angular/core'
import { contact, message } from './data'
import { BreadcrumbComponent } from '@components/breadcrumb/breadcrumb.component'
import { CommonModule } from '@angular/common'
import {
  FormsModule,
  ReactiveFormsModule,
  UntypedFormBuilder,
  UntypedFormGroup,
  Validators,
} from '@angular/forms'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [
    BreadcrumbComponent,
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    LucideAngularModule,
  ],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
  template: `
    <app-breadcrumb [pageTitle]="'Chat'" />
    <section>
      <div class="container">
        <div class="my-6 space-y-6">
          <div class="grid gap-4 lg:grid-cols-3">
            <!-- Chat List -->
            <div class="lg:col-span-1">
              <div
                class="overflow-hidden rounded-xl border border-default-200 bg-white dark:bg-default-50 lg:min-w-96"
              >
                <div class="border-b border-default-200 px-6 py-4">
                  <h6 class="text-lg font-medium text-default-900">Contacts</h6>
                </div>
                <div
                  class="h-[calc(100vh-370px)] divide-y divide-default-200 overflow-y-auto [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-default-300 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar]:w-1"
                >
                  @for (item of contactList; track $index) {
                    <div
                      id="userList"
                      [ngClass]="{
                        'bg-default-100': selectedItemIndex === $index
                      }"
                    >
                      <a
                        href="javascript:void(0);"
                        (click)="chatUsername(item.name, $index, item.avatar)"
                      >
                        <div class="flex items-center gap-3 px-4 py-3">
                          <img
                            src="{{ item.avatar }}"
                            class="h-10 rounded-full"
                            alt="Brandon Smith"
                          />
                          <div class="w-full">
                            <div class="flex justify-between">
                              <h6 class="text-default-900">{{ item.name }}</h6>
                              <small class="text-default-400">{{
                                item.time
                              }}</small>
                            </div>
                            <div class="flex justify-between">
                              <span class="font-light text-default-400">{{
                                item.message
                              }}</span>
                              @if (item.notificationCount) {
                                <span class=""
                                  ><span
                                    class="rounded-full bg-red-500/25 px-1 py-0.5 text-xs text-red-500"
                                    >{{ item.notificationCount }}</span
                                  ></span
                                >
                              }
                            </div>
                          </div>
                        </div>
                      </a>
                    </div>
                  }
                </div>
              </div>
            </div>

            <!-- Chat Conversation -->
            <div class="lg:col-span-2">
              <div
                class="w-full overflow-hidden rounded-xl border border-default-200 bg-white dark:bg-default-50"
              >
                <div class="border-b border-default-200 px-6 py-3">
                  <div
                    class="flex flex-wrap items-center justify-between gap-3 py-1.5"
                  >
                    <div class="sm:w-7/12">
                      <div class="flex items-center gap-2">
                        <img
                          src="{{ isProfile }}"
                          class="me-2 h-9 rounded-full"
                          alt="Brandon Smith"
                        />
                        <div>
                          <h5 class="text-base font-medium text-default-700">
                            {{ username }}
                          </h5>
                          <p
                            class="mt-1.5 flex items-center text-xs text-default-400"
                          >
                            <small
                              class="ti ti-circle-filled me-1 text-red-400"
                            ></small>
                            Offline
                          </p>
                        </div>
                      </div>
                    </div>

                    <div class="flex w-auto gap-1">
                      <a href="javascript: void(0);" class="inline-block p-1.5">
                        <lucide-angular
                          size="20"
                          name="phone"
                          class="flex text-default-900"
                        ></lucide-angular>
                      </a>
                      <a href="javascript: void(0);" class="inline-block p-1.5">
                        <lucide-angular
                          size="20"
                          name="video"
                          class="flex text-default-900"
                        ></lucide-angular>
                      </a>
                      <a href="javascript: void(0);" class="inline-block p-1.5">
                        <lucide-angular
                          size="20"
                          name="users"
                          class="flex text-default-900"
                        ></lucide-angular>
                      </a>
                      <a href="javascript: void(0);" class="inline-block p-1.5">
                        <lucide-angular
                          size="20"
                          name="trash-2"
                          class="flex text-default-900"
                        ></lucide-angular>
                      </a>
                    </div>
                  </div>
                </div>

                <div
                  class="h-[calc(100vh-480px)] overflow-y-auto p-6 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-default-300 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar]:w-1"
                  id="chatMessage"
                >
                  <div class="space-y-4">
                    <!-- Chat Left -->
                    @for (item of chatMessage; track $index) {
                      <div
                        class=""
                        [ngClass]="
                          item.isSender
                            ? 'group flex w-11/12 items-start gap-3 text-start'
                            : 'group ms-auto flex w-11/12 flex-row-reverse items-start gap-3 text-end'
                        "
                      >
                        <div class="text-center">
                          <img src="{{ isProfile }}" class="h-8 rounded-md" />
                          <p class="pt-0.5 text-xs">{{ item.timestamp }}</p>
                        </div>

                        <div
                          class="max-w-3/4 rounded bg-default-100 p-3"
                          [ngClass]="
                            item.isSender ? 'bg-default-100' : 'bg-primary'
                          "
                        >
                          <p
                            class="relative text-xs font-bold "
                            [ngClass]="
                              item.isSender
                                ? 'text-default-800'
                                : 'text-white/90'
                            "
                          >
                            {{ username }}
                          </p>
                          <p
                            class="pt-1"
                            [ngClass]="item.isSender ? '' : 'text-white'"
                          >
                            {{ item.content }}
                          </p>
                        </div>
                      </div>
                    }
                  </div>
                </div>

                <div
                  class="border-t border-default-200 bg-white p-6 dark:bg-default-50"
                >
                  <form
                    name="chat-form"
                    class="flex items-center gap-2"
                    (ngSubmit)="messageSave()"
                    [formGroup]="formData"
                  >
                    <input
                      type="text"
                      formControlName="content"
                      class="form-input w-full rounded border-none bg-default-100 text-default-900 placeholder:text-default-600 focus:ring-primary"
                      placeholder="Enter your text"
                      required=""
                    />
                    <div class="flex w-auto gap-1">
                      <a
                        href="javascript:void(0);"
                        class="rounded bg-default-200 px-3 py-2 text-default-800 hover:bg-default-800/20"
                        ><lucide-angular
                          name="paperclip"
                          class="inline size-3.5 text-default-800"
                        ></lucide-angular
                      ></a>
                      <button
                        class="inline-flex items-center justify-center gap-2 rounded bg-primary px-3 py-2 text-white transition-all duration-300 hover:bg-primary-700"
                      >
                        Send
                        <lucide-angular
                          name="send"
                          class="size-4"
                        ></lucide-angular>
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
  styles: ``,
})
export class ChatComponent {
  contactList = contact
  submitted!: boolean
  username: string = 'Brandon Smith'
  isProfile: string = 'assets/images/avatars/img-2.jpg'
  formData!: UntypedFormGroup
  selectedItemIndex: number | null = null
  isreplyMessage = false
  chatMessage: any
  isCurrentUserSender: boolean = true
  @ViewChild('chatContainer', { static: false }) chatContainer!: ElementRef

  constructor(
    public formBuilder: UntypedFormBuilder,
    private renderer: Renderer2
  ) {}

  ngOnInit(): void {
    this.renderer.addClass(document.body, 'bg-default-50')
    this.chatMessage = message
    // Validation
    this.formData = this.formBuilder.group({
      content: ['', [Validators.required]],
    })
  }

  /**
   *
   * Returns form
   */
  get form() {
    return this.formData.controls
  }
  // chat page change
  chatUsername(name: string, index: number, avatar: string): void {
    // Handle the click event here
    this.selectedItemIndex = index
    this.username = name
    this.isProfile = avatar
  }

  /**
   * Save the message in chat
   */
  messageSave() {
    const content = this.formData.get('content')!.value
    if (this.formData.valid && content) {
      // User message
      this.chatMessage.push({
        id: this.chatMessage.length + 1,
        content,
        isSender: false,
        sender: '',
      })

      // System-generated reply
      setTimeout(() => {
        this.chatMessage.push({
          id: this.chatMessage.length + 1,
          content,
          isSender: true,
          sender: '',
        })
        this.isCurrentUserSender = !this.isCurrentUserSender
        this.onListScroll()
      }, 1000)
      this.onListScroll()
      // Toggle sender status for the next message
    }
    // this.scrollToBottom();
    this.formData.reset()
  }

  // list scroll
  onListScroll() {
    const containerElement = document.getElementById('chatMessage') // Replace 'yourContainerId' with the actual ID of your container element

    if (containerElement) {
      setTimeout(() => {
        containerElement.scrollTop = containerElement.scrollHeight
      }, 100)
    }
  }
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/admin/chat/components/Chat.vue
<template>
  <div
    class="w-full overflow-hidden rounded-xl border border-default-200 bg-white dark:bg-default-50"
  >
    <div class="border-b border-default-200 px-6 py-3">
      <div class="flex flex-wrap items-center justify-between gap-3 py-1.5">
        <div class="sm:w-7/12">
          <div class="flex items-center gap-2">
            <img :src="avatar5" class="me-2 h-9 rounded-full" alt="" />
            <div>
              <h5 class="text-base font-medium text-default-700">John Kish</h5>
              <p class="mt-1.5 flex items-center text-xs text-default-400">
                <CircleIcon class="me-1 text-red-400 h-3 w-3 fill-red-400" />
                Offline
              </p>
            </div>
          </div>
        </div>

        <div class="w-auto flex items-center">
          <a href="javascript: void(0);" class="inline-block p-1.5">
            <PhoneIcon class="text-default-900 w-5 h-5" />
          </a>
          <a href="javascript: void(0);" class="inline-block p-1.5">
            <VideoIcon class="text-default-900 w-5 h-5" />
          </a>
          <a href="javascript: void(0);" class="inline-block p-1.5">
            <UsersIcon class="text-default-900 w-5 h-5" />
          </a>
          <a href="javascript: void(0);" class="inline-block p-1.5">
            <Trash2Icon class="text-default-900 w-5 h-5" />
          </a>
        </div>
      </div>
    </div>

    <div
      class="h-[calc(100vh-480px)] overflow-y-auto p-6 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-default-300 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar]:w-1"
    >
      <div class="space-y-4">
        <!-- Chat Left -->
        <div
          v-for="(item, idx) in conversationData"
          :key="idx"
          class="flex w-11/12 gap-3"
          :class="item.isCurrent ? 'ms-auto flex-row-reverse text-end' : 'group text-start'"
        >
          <div class="text-center">
            <img :src="item.user.image" class="h-8 rounded-md" />
            <p class="pt-0.5 text-xs">{{ item.time }}</p>
          </div>

          <div class="max-w-3/4">
            <div class="rounded p-3" :class="item.isCurrent ? 'bg-primary' : 'bg-default-100'">
              <p
                class="relative text-xs font-bold"
                :class="item.isCurrent ? 'text-white/90' : 'text-default-800'"
              >
                {{ item.user.name }}
              </p>
              <p class="pt-1" :class="{ 'text-white/90': item.isCurrent }">{{ item.message }}</p>
            </div>

            <div
              v-if="idx == conversationData.length - 1"
              class="mt-3 rounded border border-default-200"
            >
              <div class="p-3">
                <div class="flex items-center justify-between gap-3">
                  <div class="flex items-center gap-3">
                    <div class="h-12 w-12">
                      <span
                        class="inline-flex h-full w-full items-center justify-center rounded bg-primary text-white"
                      >
                        .ZIP
                      </span>
                    </div>
                    <div class="text-start text-default-400">
                      <a href="javascript:void(0);" class="text-sm font-bold">sketch.zip</a>
                      <p class="text-sm">2.3 MB</p>
                    </div>
                  </div>
                  <a href="javascript:void(0);" class="btn !text-xl">
                    <DownloadIcon class="h-5 w-5" />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="border-t border-default-200 bg-white p-6 dark:bg-default-50">
      <form name="chat-form" class="flex items-center gap-2">
        <input
          type="text"
          class="form-input w-full rounded border-none bg-default-100 text-default-900 placeholder:text-default-600 focus:ring-primary"
          placeholder="Enter your text"
          required
        />
        <div class="flex w-auto gap-1">
          <a
            href="#"
            class="rounded bg-default-200 px-3 py-2 text-default-800 hover:bg-default-800/20"
          >
            <PaperclipIcon class="h-4 w-4" />
          </a>
          <button
            class="inline-flex items-center justify-center gap-2 rounded bg-primary px-3 py-2 text-white transition-all duration-300 hover:bg-primary-700"
          >
            Send
            <SendIcon class="h-4 w-4" />
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
CircleIcon,
DownloadIcon,
PaperclipIcon,
PhoneIcon,
SendIcon,
Trash2Icon,
UsersIcon,
VideoIcon
} from 'lucide-vue-next'

import type { UserType } from '@/types/admin'

type ConversationType = {
  user: UserType
  time: string
  message: string
  isCurrent?: boolean
}

import avatar1 from '@/assets/images/avatars/img-1.jpg'
import avatar5 from '@/assets/images/avatars/img-5.jpg'

const userData: UserType[] = [
  {
    image: avatar5,
    name: 'John K'
  },
  {
    image: avatar1,
    name: 'Diane B'
  }
]

const conversationData: ConversationType[] = [
  {
    user: userData[0],
    time: '10:00',
    message: 'Hello!'
  },
  {
    user: userData[1],
    time: '10:01',
    message: 'Hi, How are you? What about our next meeting?',
    isCurrent: true
  },
  {
    user: userData[0],
    time: '10:01',
    message: 'Yeah everything is fine'
  },
  {
    user: userData[1],
    time: '10:02',
    message: `Wow that's great`,
    isCurrent: true
  },
  {
    user: userData[0],
    time: '10:02',
    message: `Let's have it today if you are free`
  },
  {
    user: userData[1],
    time: '10:03',
    message: `Sure thing! let me know if 2pm works for you`,
    isCurrent: true
  },
  {
    user: userData[0],
    time: '10:04',
    message: `Sorry, I have another meeting scheduled at 2pm. Can we have it at 3pm instead?`
  },
  {
    user: userData[0],
    time: '10:04',
    message: `We can also discuss about the presentation talk format if you have some extra mins`
  },
  {
    user: userData[1],
    time: '10:05',
    message: `3pm it is. Sure, let's discuss about presentation format, it would be great to finalize today. I am attaching the last year format and assets here...`,
    isCurrent: true
  }
]
</script>
