// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Ebook/components/Hero.tsx
import { Link } from 'react-router-dom'

import ebook16 from '@/assets/images/landing/ebook/img-16.jpg'
import ebook17 from '@/assets/images/landing/ebook/img-17.jpg'
import ebookBackground from '@/assets/images/landing/ebook/bg-2.png'

const Hero = () => {
  return (
    <section id="home" className="pb-40 pt-40 flex items-center justify-center relative overflow-hidden bg-cover bg-gradient-to-l from-primary-500/5 to-primary-500/10 via-primary-500/0">
      <div className="absolute top-1/4 start-[10%] -z-1 hidden 2xl:block">
        <img src={ebookBackground} className="h-28" />
      </div>
      <div className="container">
        <div className="grid xl:grid-cols-2 grid-cols-1 gap-6 relative items-center">
          <div className="col-span-1">
            <span className="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary">Digital Ebooks</span>
            <h2 className="md:text-5xl/tight text-4xl font-medium text-default-950 my-5">Ebooks to Foster Your Personal and Professional Development</h2>
            <p className="text-base text-default-950 mb-10">Our meticulously selected ebooks ensure a top-notch reading journey, spanning across fiction, non-fiction, self-help, and educational genres.</p>
            <div className="flex flex-wrap items-center gap-6 mt-10">
              <Link to="" className="text-lg py-2 px-8 rounded-lg text-white border border-primary bg-primary/90 hover:border-primary hover:bg-primary transition-all duration-700">Download Now</Link>
              <Link to="" className="text-lg font-medium py-2 px-8 rounded-lg border border-primary text-primary hover:border-primary hover:text-white hover:bg-primary transition-all duration-700">Browse Ebook</Link>
            </div>
          </div>
          <div className="col-span-1">
            <div className="flex items-end justify-center">
              <div className="-me-40 z-10 hidden md:block">
                <img src={ebook17} className="h-60 rounded-tr-[90px] rounded-bl-[90px] border-4 border-default-100" />
              </div>
              <div className="relative">
                <img src={ebook16} className="h-[500px] rounded-t-full" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Hero

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/ebook/hero.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [],

  template: ` <!-- Hero Section Start -->
    <section
      id="home"
      class="relative flex items-center justify-center overflow-hidden bg-gradient-to-l from-primary-500/5 via-primary-500/0 to-primary-500/10 bg-cover pb-40 pt-40"
    >
      <div class="-z-1 absolute start-[10%] top-1/4 hidden 2xl:block">
        <img src="assets/images/landing/ebook/bg-2.png" class="h-28" alt="" />
      </div>

      <div class="container">
        <div
          class="relative grid grid-cols-1 items-center gap-6 xl:grid-cols-2"
        >
          <div class="col-span-1">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Digital Ebooks</span
            >
            <h2
              class="my-5 text-4xl font-medium text-default-950 md:text-5xl/tight"
            >
              Ebooks to Foster Your Personal and Professional Development
            </h2>
            <p class="mb-10 text-base text-default-950">
              Our meticulously selected ebooks ensure a top-notch reading
              journey, spanning across fiction, non-fiction, self-help, and
              educational genres.
            </p>
            <div class="mt-10 flex flex-wrap items-center gap-6">
              <a
                href="javascript:void(0);"
                class="rounded-lg border border-primary bg-primary/90 px-8 py-2 text-lg text-white transition-all duration-300 hover:border-primary hover:bg-primary"
                >Download Now</a
              >
              <a
                href="javascript:void(0);"
                class="rounded-lg border border-primary px-8 py-2 text-lg font-medium text-primary transition-all duration-300 hover:border-primary hover:bg-primary hover:text-white"
                >Browse Ebook</a
              >
            </div>
            <!-- flex End -->
          </div>
          <div class="col-span-1">
            <div class="flex items-end justify-center">
              <div class="z-10 -me-40 hidden md:block">
                <img
                  src="assets/images/landing/ebook/img-17.jpg"
                  class="h-60 rounded-bl-[90px] rounded-tr-[90px] border-4 border-default-100"
                  alt=""
                />
              </div>
              <div class="relative">
                <img
                  src="assets/images/landing/ebook/img-16.jpg"
                  class="h-[500px] rounded-t-full"
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- container End -->
    </section>
    <!-- Hero end -->`,
  styles: ``,
})
export class HeroComponent {}
