// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/web-designer/stories.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-stories',
  standalone: true,
  imports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
  template: `
    <section id="stories" class="py-10 lg:py-20">
      <div class="container">
        <div class="mx-auto mb-12 max-w-xl text-center">
          <span
            class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
            >Featured Stories</span
          >
          <h2 class="mt-3 text-3xl font-medium text-default-950 md:text-4xl">
            Latest News
          </h2>
          <p class="mt-5 text-base">
            Proin faucibus arcu quis ante. In consectetuer turpis ut velit.
          </p>
        </div>

        <div>
          <div class="relative border-y border-default-200 p-10">
            <div class="grid grid-cols-1 gap-6 lg:grid-cols-12">
              <div class="lg:col-span-3">
                <div class="flex items-center">
                  <div class="mr-5">
                    <div class="img size-14 overflow-hidden rounded-full">
                      <img
                        src="assets/images/avatars/img-1.jpg"
                        class="h-full w-full"
                        alt=""
                      />
                    </div>
                  </div>
                  <div>
                    <span class="mb-5 text-sm font-medium">Posted by</span>
                    <h6 class="text-xl font-medium text-default-950">
                      Olivia Rhye
                    </h6>
                  </div>
                </div>
              </div>
              <!-- col-span-3 End -->

              <div class="lg:col-span-6">
                <h5 class="mb-10 underline">
                  <a
                    href="javascript:void(0);"
                    class="text-xl font-medium text-default-950"
                    >Natura Insects Series: Shaping Insects from Flowers</a
                  >
                </h5>
                <div class="flex items-center gap-7">
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Design</a
                  >
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Marketing</a
                  >
                </div>
              </div>
              <!-- col-span-6 End -->
              <div class="flex items-center lg:col-span-3 lg:justify-end">
                <span class="text-base font-medium">December 3, 2023</span>
              </div>
              <!-- col-span-3 End -->
            </div>
            <!-- Grid End -->
            <div
              class="background absolute left-0 top-0 h-full w-full bg-cover bg-top text-center opacity-0 hover:bg-bottom hover:opacity-100"
              style="
                background-image: url(assets/images/landing/web-designer/img-10.jpg);
                transition:
                  opacity 0.4s,
                  background-position 10s linear;
              "
            >
              <div class="flex h-full items-center justify-center">
                <a
                  href="javascript:void(0);"
                  class="inline-flex items-center justify-center gap-1 rounded-md bg-primary px-6 py-2 text-white transition-all duration-300 hover:bg-primary-700"
                >
                  Read More<lucide-angular
                    name="move-right"
                    class="size-5"
                  ></lucide-angular>
                </a>
              </div>
              <!-- flex End -->
            </div>
          </div>

          <div class="relative p-10">
            <div class="grid gap-6 lg:grid-cols-12">
              <div class="lg:col-span-3">
                <div class="flex items-center">
                  <div class="mr-5">
                    <div class="img size-14 overflow-hidden rounded-full">
                      <img
                        src="assets/images/avatars/img-3.jpg"
                        class="h-full w-full"
                        alt=""
                      />
                    </div>
                  </div>
                  <div>
                    <span class="mb-5 text-sm font-medium">Posted by</span>
                    <h6 class="text-xl font-medium text-default-950">
                      Olivia Rhye
                    </h6>
                  </div>
                </div>
              </div>
              <!-- col-span-3 End -->
              <div class="lg:col-span-6">
                <h5 class="mb-10 underline">
                  <a
                    href="javascript:void(0);"
                    class="text-xl font-medium text-default-950"
                    >Minimalistic Design Concept for Balmain Online Store</a
                  >
                </h5>
                <div class="flex items-center gap-7">
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Design</a
                  >
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Marketing</a
                  >
                </div>
              </div>
              <!-- col-span-6 End -->
              <div class="flex items-center lg:col-span-3 lg:justify-end">
                <span class="text-base font-medium">December 2, 2023</span>
              </div>
              <!-- col-span-3 End -->
            </div>
            <!-- Grid End -->
            <div
              class="background absolute left-0 top-0 h-full w-full bg-cover bg-top text-center opacity-0 hover:bg-bottom hover:opacity-100"
              style="
                background-image: url(assets/images/landing/web-designer/img-9.jpg);
                transition:
                  opacity 0.4s,
                  background-position 10s linear;
              "
            >
              <div class="flex h-full items-center justify-center">
                <a
                  href="javascript:void(0);"
                  class="inline-flex items-center justify-center gap-1 rounded-md bg-primary px-6 py-2 text-white transition-all duration-300 hover:bg-primary-700"
                >
                  Read More<lucide-angular
                    name="move-right"
                    class="size-5"
                  ></lucide-angular>
                </a>
              </div>
              <!-- flex End -->
            </div>
          </div>

          <div class="relative border-y border-default-200 p-10">
            <div class="grid gap-6 lg:grid-cols-12">
              <div class="lg:col-span-3">
                <div class="flex items-center">
                  <div class="mr-5">
                    <div class="img size-14 overflow-hidden rounded-full">
                      <img
                        src="assets/images/avatars/img-2.jpg"
                        class="h-full w-full"
                        alt=""
                      />
                    </div>
                  </div>
                  <div>
                    <span class="mb-5 text-sm font-medium">Posted by</span>
                    <h6 class="text-xl font-medium text-default-950">
                      Olivia Rhye
                    </h6>
                  </div>
                </div>
              </div>
              <!-- col-span-3 End -->
              <div class="lg:col-span-6">
                <h5 class="mb-10 underline">
                  <a
                    href="javascript:void(0);"
                    class="text-xl font-medium text-default-950"
                    >Spotlight on the Equinox Collection by Shane Griffin</a
                  >
                </h5>
                <div class="flex items-center gap-7">
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Design</a
                  >
                  <a
                    href="javascript:void(0);"
                    class="text-sm uppercase tracking-widest text-default-950"
                    >Marketing</a
                  >
                </div>
              </div>
              <!-- col-span-6 End -->
              <div class="flex items-center lg:col-span-3 lg:justify-end">
                <span class="text-base font-medium">November 29, 2023</span>
              </div>
              <!-- col-span-3 End -->
            </div>
            <!-- Grid End -->
            <div
              class="background absolute left-0 top-0 h-full w-full bg-cover bg-top text-center opacity-0 hover:bg-bottom hover:opacity-100"
              style="
                background-image: url(assets/images/landing/web-designer/img-8.jpg);
                transition:
                  opacity 0.4s,
                  background-position 10s linear;
              "
            >
              <div class="flex h-full items-center justify-center">
                <a
                  href="javascript:void(0);"
                  class="inline-flex items-center justify-center gap-1 rounded-md bg-primary px-6 py-2 text-white transition-all duration-300 hover:bg-primary-700"
                >
                  Read More<lucide-angular
                    name="move-right"
                    class="size-5"
                  ></lucide-angular>
                </a>
              </div>
              <!-- flex End -->
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
  styles: ``,
})
export class StoriesComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/WebDesigner/components/Stories.tsx
import { Link } from "react-router-dom"
import { stories } from "../data"
import { cn } from "@/utils"
import { LuMoveRight } from "react-icons/lu"

const Stories = () => {
  return (
    <section id="stories" className="py-10 lg:py-20">
      <div className="container">
        <div className="mx-auto mb-12 max-w-xl text-center">
          <span className="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary">Featured Stories</span>
          <h2 className="mt-3 text-3xl font-medium text-default-950 md:text-4xl">
            Latest News
          </h2>
          <p className="mt-5 text-base">
            Proin faucibus arcu quis ante. In consectetuer turpis ut velit.
          </p>
        </div>

        <div>
          {stories.map((story, idx) => {
            return (
              <div key={idx} className={cn("relative p-10", idx == 0 ? "border-y border-default-200" : "border-b border-default-200")}>
                <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
                  <div className="lg:col-span-3">
                    <div className="flex items-center">
                      <div className="mr-5">
                        <div className="img size-14 overflow-hidden rounded-full">
                          <img src={story.image} className="h-full w-full" alt="" />
                        </div>
                      </div>
                      <div>
                        <span className="mb-5 text-sm font-medium">Posted by</span>
                        <h6 className="text-xl font-medium text-default-950">
                          Olivia Rhye
                        </h6>
                      </div>
                    </div>
                  </div>

                  <div className="lg:col-span-6">
                    <h5 className="mb-10 underline">
                      <Link to="" className="text-xl font-medium text-default-950"
                      >{story.title}</Link>
                    </h5>
                    <div className="flex items-center gap-7">
                      <Link to="" className="text-sm uppercase tracking-widest text-default-950" >Design</Link>
                      <Link to="" className="text-sm uppercase tracking-widest text-default-950">Marketing</Link>
                    </div>
                  </div>

                  <div className="flex items-center lg:col-span-3 lg:justify-end">
                    <span className="text-base font-medium">{story.date}</span>
                  </div>

                </div>

                <div className="background absolute left-0 top-0 h-full w-full bg-cover bg-top text-center opacity-0 hover:bg-bottom hover:opacity-100" style={{ backgroundImage: `url(${story.backgroundImage})`, transition: "opacity 0.4s, background-position 10s linear" }}>
                  <div className="flex h-full items-center justify-center">
                    <Link to="" className="inline-flex items-center justify-center gap-1 rounded-md bg-primary px-6 py-2 text-white transition-all duration-300 hover:bg-primary-700">
                      Read More<LuMoveRight className="size-5" />
                    </Link>
                  </div>
                </div>
              </div>
            )
          })}

        </div>
      </div>
    </section>
  )
}

export default Stories
