// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/marketing2/hero.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [],
  template: `
    <!-- Hero Section Start -->
    <section
      id="home"
      class="relative flex items-center justify-center overflow-hidden py-[164px]"
    >
      <div class="absolute inset-0">
        <img
          src="assets/images/landing/marketing-2/mbg-2.png"
          class="h-full w-full dark:hidden"
          alt=""
        />
        <img
          src="assets/images/landing/marketing-2/bg-2-dark.jpg"
          class="hidden h-full w-full dark:block"
          alt=""
        />
      </div>

      <div class="container">
        <div class="relative">
          <div class="grid items-center gap-6 lg:grid-cols-2">
            <div class="mx-auto max-w-md text-center lg:ms-0 lg:text-start">
              <span
                class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
                >startups Marketing</span
              >
              <h2
                class="my-5 text-4xl font-medium text-default-950 md:text-5xl/tight"
              >
                Global Marketing Consulting Firm
              </h2>
              <p class="mb-10 text-base">
                We are a worldwide marketing consultancy providing innovative
                solutions to our clientele.
              </p>
              <a
                href="javascript:void(0);"
                class="rounded-md bg-primary px-6 py-3 text-white transition-all duration-300 hover:bg-primary-700"
                >Reach Out to Us</a
              >
            </div>
            <!-- col End -->

            <div>
              <div class="relative">
                <img
                  src="assets/images/landing/marketing-2/img-1.jpg"
                  class="mx-auto rounded-3xl"
                  alt=""
                />

                <div class="hidden xl:block">
                  <div class="absolute -start-52 top-10">
                    <div class="inline-block">
                      <div
                        class="rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80"
                      >
                        <div class="max-w-sm px-4 py-4 text-center">
                          <p class="text-base text-default-950">
                            Donec pede justo, fringilla vel, aliquet nec,
                            vulputate eget, arcu.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="absolute -end-40 bottom-20 top-auto">
                    <div>
                      <div
                        class="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80"
                      >
                        <div class="px-5 py-3">
                          <h5 class="text-base font-medium">
                            Marketing Consulting
                          </h5>
                        </div>
                      </div>
                    </div>

                    <div class="my-2">
                      <div
                        class="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80"
                      >
                        <div class="px-5 py-3">
                          <h5 class="text-base font-medium">
                            Social Media Marketing
                          </h5>
                        </div>
                      </div>
                    </div>

                    <div>
                      <div
                        class="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80"
                      >
                        <div class="px-5 py-3">
                          <h5 class="text-base font-medium">
                            Search Engine Optimization
                          </h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- col End -->
          </div>
          <!-- grid End -->
        </div>
      </div>
      <!-- container End -->
    </section>
    <!-- Hero Section End -->
  `,
  styles: ``,
})
export class HeroComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Marketing2/components/Hero.tsx
import backgroundImg from '@/assets/images/landing/marketing-2/bg-2.png'
import backgroundDarkImg from '@/assets/images/landing/marketing-2/bg-2-dark.jpg'

import marketing1 from '@/assets/images/landing/marketing-2/img-1.jpg'
import { Link } from 'react-router-dom'

const Hero = () => {
  return (
    <section id="home" className="py-[164px] relative overflow-hidden flex items-center justify-center">
      <div className="absolute inset-0">
        <img src={backgroundImg} className="dark:hidden h-full w-full" />
        <img src={backgroundDarkImg} className="hidden dark:block h-full w-full" />
      </div>
      <div className="container">
        <div className="relative">
          <div className="grid lg:grid-cols-2 gap-6 items-center">
            <div className="max-w-md mx-auto text-center lg:ms-0 lg:text-start">
              <span className="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary">startups Marketing</span>
              <h2 className="md:text-5xl/tight text-4xl font-medium text-default-950 my-5">Global Marketing Consulting Firm</h2>
              <p className="text-base mb-10">We are a worldwide marketing consultancy providing innovative solutions to our clientele.</p>
              <Link to="" className="px-6 py-3 rounded-md text-white bg-primary hover:bg-primary-700 transition-all duration-300">Reach Out to Us</Link>
            </div>
            <div>
              <div className="relative">
                <img src={marketing1} className="rounded-3xl mx-auto" />
                <div className="hidden xl:block">
                  <div className="absolute top-10 -start-52">
                    <div className="inline-block">
                      <div className="rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80">
                        <div className="max-w-sm text-center px-4 py-4">
                          <p className="text-base text-default-950">Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="absolute top-auto bottom-20 -end-40">
                    <div>
                      <div className="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80">
                        <div className="py-3 px-5">
                          <h5 className="text-base font-medium">Marketing Consulting</h5>
                        </div>
                      </div>
                    </div>
                    <div className="my-2">
                      <div className="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80">
                        <div className="py-3 px-5">
                          <h5 className="text-base font-medium">Social Media Marketing</h5>
                        </div>
                      </div>
                    </div>
                    <div>
                      <div className="inline-block rounded-full border border-default-200 bg-white/80 shadow backdrop-blur-lg dark:bg-black/80">
                        <div className="py-3 px-5">
                          <h5 className="text-base font-medium">Search Engine Optimization</h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Hero
