// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/marketing2/investment-steps.component.ts
import { Component } from '@angular/core'
import { VideoPlayerComponent } from '@components/video-player.component'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-investment-steps',
  standalone: true,
  imports: [VideoPlayerComponent, LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],

  template: `
    <div
      class="absolute inset-0 bg-[url(../images/landing/marketing-2/img-8.jpg)] bg-cover bg-center bg-repeat"
    >
      <div class="absolute inset-0 h-full w-full bg-black/50"></div>
    </div>

    <div class="relative">
      <div class="grid items-center gap-6 sm:grid-cols-3">
        <div class="sm:col-span-2">
          <div class="rounded-md p-6">
            <h2 class="text-center text-4xl font-medium text-white">
              Achieving Success in Three Simple Investment Steps
            </h2>

            <div class="mt-10 grid grid-cols-1 gap-6">
              <div
                class="rounded-md bg-white/60 p-6 backdrop-blur-xl dark:bg-black/60"
              >
                <div class="flex flex-wrap items-center gap-6 md:flex-nowrap">
                  <div>
                    <lucide-angular
                      name="map-pin"
                      class="size-12 stroke-primary"
                    ></lucide-angular>
                  </div>
                  <div>
                    <h2 class="text-2xl font-medium text-default-950">
                      Crafting Your Path Forward
                    </h2>
                    <p class="mt-3 text-base text-default-950">
                      Businesses purchase products in substantial quantities for
                      distribution to consumers.
                    </p>
                  </div>
                </div>
                <!-- flex End -->
              </div>
              <!-- col End -->

              <div
                class="rounded-md bg-white/60 p-6 backdrop-blur-xl dark:bg-black/60"
              >
                <div class="flex flex-wrap items-center gap-6 md:flex-nowrap">
                  <div>
                    <lucide-angular
                      name="send"
                      class="size-12 stroke-primary"
                    ></lucide-angular>
                  </div>
                  <div>
                    <h2 class="text-2xl font-medium text-default-950">
                      Executing Your Strategy
                    </h2>
                    <p class="mt-3 text-base text-default-950">
                      Consumers acquire products in smaller volumes suited for
                      personal use.
                    </p>
                  </div>
                </div>
                <!-- flex End -->
              </div>
              <!-- col End -->

              <div
                class="rounded-md bg-white/60 p-6 backdrop-blur-xl dark:bg-black/60"
              >
                <div class="flex flex-wrap items-center gap-6 md:flex-nowrap">
                  <div>
                    <lucide-angular
                      name="network"
                      class="size-12 stroke-primary"
                    ></lucide-angular>
                  </div>
                  <div>
                    <h2 class="text-2xl font-medium text-default-950">
                      Enhancing Through Empowerment
                    </h2>
                    <p class="mt-3 text-base text-default-950">
                      The market for businesses to target is relatively smaller
                      compared to direct consumers.
                    </p>
                  </div>
                </div>
                <!-- flex End -->
              </div>
              <!-- col End -->
            </div>
            <!-- Grid End -->
          </div>
        </div>
        <!-- col-span-2 End -->

        <div class="relative h-full">
          <div class="flex h-full items-center justify-center">
            <app-video-player [classname]="classname" />
          </div>
        </div>
      </div>
    </div>

    <!-- Watch Video Modal Start -->

    <!-- Watch Video Modal End -->
  `,
  styles: ``,
})
export class InvestmentStepsComponent {
  classname =
    'relative flex size-20 items-center justify-center gap-2.5 rounded-full bg-primary text-base font-medium text-white ring-4 ring-primary/25 transition-all duration-300 hover:bg-primary'
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Marketing2/components/InvestmentSteps.tsx
import { LuPlay } from "react-icons/lu"
import { investmentSteps } from "../data"

const InvestmentSteps = () => {
  return (
    <>
      <section className="py-16 lg:py-32 h-full relative">
        <div className="container">
          <div className="absolute inset-0 bg-cover bg-repeat bg-center bg-[url(../images/landing/marketing-2/img-8.jpg)]">
            <div className="absolute inset-0 w-full h-full bg-black/50" />
          </div>
          <div className="relative">
            <div className="grid sm:grid-cols-3 gap-6 items-center">
              <div className="sm:col-span-2">
                <div className="p-6 rounded-md">
                  <h2 className="text-4xl font-medium text-white text-center">Achieving Success in Three Simple Investment Steps</h2>
                  <div className="grid grid-cols-1 gap-6 mt-10">
                    {investmentSteps.map((step, idx) => {
                      const Icon = step.icon
                      return (
                        <div key={idx} className="p-6 rounded-md bg-white/60 dark:bg-black/60 backdrop-blur-xl">
                          <div className="flex flex-wrap md:flex-nowrap items-center gap-6">
                            <div>
                              <Icon className="h-12 w-12 stroke-primary" />
                            </div>
                            <div>
                              <h2 className="text-2xl font-medium text-default-950">{step.title}</h2>
                              <p className="text-base text-default-950 mt-3">{step.description}</p>
                            </div>
                          </div>
                        </div>
                      )
                    })}
                  </div>
                </div>
              </div>
              <div className="relative h-full">
                <div className="flex items-center justify-center h-full">
                  <button className="relative h-20 w-20 flex items-center justify-center gap-2.5 rounded-full text-base font-medium bg-primary text-white transition-all duration-300 ring-4 ring-primary/25 hover:bg-primary" data-hs-overlay="#watchvideomodal">
                    <LuPlay className="h-7 w-7 fill-current" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div id="watchvideomodal" className="hs-overlay hidden w-full h-full fixed top-0 start-0 z-[80] overflow-x-hidden overflow-y-auto pointer-events-none">
        <div className="hs-overlay-open:mt-7 hs-overlay-open:opacity-100 hs-overlay-open:duration-500 mt-0 opacity-0 ease-out transition-all sm:max-w-xl sm:w-full m-3 sm:mx-auto min-h-[calc(100%-3.5rem)] flex items-center">
          <div className="w-full flex flex-col pointer-events-auto rounded-xl overflow-x-hidden">
            <iframe className="w-full" height={400} src="https://www.youtube.com/embed/NbR-wVOpJwA?si=OlR2e-UItbGilVlu" title="YouTube video player" frameBorder={0} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />
          </div>
        </div>
      </div>
    </>
  )
}

export default InvestmentSteps
