// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Company/index.jsx
import { PageMetaData, TopNavBar } from "@/components";
import Hero from "./components/Hero";
import Brands from "./components/Brands";
import Contact from "./components/Contact";
import Services from "./components/Services";
import FAQs from "./components/FAQs";
import TestimonialSlider from "./components/TestimonialSlider";
import Blogs from "./components/Blogs";

const Company = () => {
  return (
    <>
      <PageMetaData title="Company" />

      <TopNavBar
        menuItems={["home", "services", "faq", "testimonials", "blog"]}
        position="fixed"
        hasDownloadButton
      />

      <Hero />

      <Brands />

      <Contact />

      <Services />

      <FAQs />

      <TestimonialSlider />

      <Blogs />
    </>
  );
};

export default Company;

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/company/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import Contact from './Contact.svelte';
	import Service from './Service.svelte';
	import Stat from './Stat.svelte';
	import Faq from './Faq.svelte';
	import Testimonial from './Testimonial.svelte';
	import Blog from './Blog.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'services',
			name: 'Services'
		},
		{
			id: 'faq',
			name: 'Faq'
		},
		{
			id: 'testimonials',
			name: 'Testimonials'
		},
		{
			id: 'blog',
			name: 'Blog'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<Contact />

<Service />

<Stat />

<Faq />

<Testimonial />

<Blog />
