// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Vue/Vue/src/views/landings/portfolio-2/index.vue
<template>
  <Navbar1 menu-position="fixed" :navbar-link="navLinkData" btn-text="Download" :btn-icon="DownloadCloudIcon" />

  <Portfolio2Hero />

  <section>
    <MarqueeGroup custom-class="bg-black" text-class="text-white" />
  </section>

  <About />

  <Project />

  <Advantage />

  <Accolades />

  <Testimonial />

  <Blog />

  <Cta />

  <Footer />

  <BackToTop />
</template>

<script setup lang="ts">
import Navbar1 from '@/layout/partials/Navbar1.vue'
import Portfolio2Hero from '@/components/heros/Portfolio2Hero.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import About from '@/views/landings/portfolio-2/About.vue'
import Project from '@/views/landings/portfolio-2/Project.vue'
import Advantage from '@/views/landings/portfolio-2/Advantage.vue'
import Accolades from '@/views/landings/portfolio-2/Accolades.vue'
import Testimonial from '@/views/landings/portfolio-2/Testimonial.vue'
import Blog from '@/views/landings/portfolio-2/Blog.vue'
import Cta from '@/views/landings/portfolio-2/Cta.vue'
import Footer from '@/layout/partials/Footer.vue'
import BackToTop from '@/layout/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home',
  },
  {
    id: 'about',
    name: 'About',
  },
  {
    id: 'project',
    name: 'Project',
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
  },
  {
    id: 'advantage',
    name: 'Advantage',
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
  },
  {
    id: 'blog',
    name: 'Blog',
  },
]
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/portfolio-2/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import About from './About.svelte';
	import Project from './Project.svelte';
	import Advantage from './Advantage.svelte';
	import Accolades from './Accolades.svelte';
	import Testimonial from './Testimonial.svelte';
	import Blog from './Blog.svelte';
	import Cta from './Cta.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'project',
			name: 'Project'
		},
		{
			id: 'portfolio',
			name: 'Portfolio'
		},
		{
			id: 'advantage',
			name: 'Advantage'
		},
		{
			id: 'testimonial',
			name: 'Testimonial'
		},
		{
			id: 'blog',
			name: 'Blog'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<section>
	<MarqueeGroup customClass="bg-black" textClass="text-white" />
</section>

<About />

<Project />

<Advantage />

<Accolades />

<Testimonial />

<Blog />

<Cta />
