// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/portfolio-2/index.vue
<template>
  <Navbar1
    menu-position="fixed"
    :navbar-link="navLinkData"
    btn-text="Download"
    :btn-icon="DownloadCloudIcon"
  />

  <Portfolio2Hero />

  <section>
    <MarqueeGroup custom-class="bg-black" text-class="text-white" />
  </section>

  <About />

  <Project />

  <Advantage />

  <Accolades />

  <Testimonial />

  <Blog />

  <Cta />

  <Footer />

  <client-only>
    <BackToTop />
  </client-only>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

import Navbar1 from '@/layouts/partials/Navbar1.vue'
import Portfolio2Hero from '@/components/heros/Portfolio2Hero.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import About from '@/pages/landings/portfolio-2/components/About.vue'
import Project from '@/pages/landings/portfolio-2/components/Project.vue'
import Advantage from '@/pages/landings/portfolio-2/components/Advantage.vue'
import Accolades from '@/pages/landings/portfolio-2/components/Accolades.vue'
import Testimonial from '@/pages/landings/portfolio-2/components/Testimonial.vue'
import Blog from '@/pages/landings/portfolio-2/components/Blog.vue'
import Cta from '@/pages/landings/portfolio-2/components/Cta.vue'
import Footer from '@/layouts/partials/Footer.vue'
import BackToTop from '@/layouts/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home'
  },
  {
    id: 'about',
    name: 'About'
  },
  {
    id: 'project',
    name: 'Project'
  },
  {
    id: 'portfolio',
    name: 'Portfolio'
  },
  {
    id: 'advantage',
    name: 'Advantage'
  },
  {
    id: 'testimonial',
    name: 'Testimonial'
  },
  {
    id: 'blog',
    name: 'Blog'
  }
]
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/portfolio-2/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import About from './About.svelte';
	import Project from './Project.svelte';
	import Advantage from './Advantage.svelte';
	import Accolades from './Accolades.svelte';
	import Testimonial from './Testimonial.svelte';
	import Blog from './Blog.svelte';
	import Cta from './Cta.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'project',
			name: 'Project'
		},
		{
			id: 'portfolio',
			name: 'Portfolio'
		},
		{
			id: 'advantage',
			name: 'Advantage'
		},
		{
			id: 'testimonial',
			name: 'Testimonial'
		},
		{
			id: 'blog',
			name: 'Blog'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<section>
	<MarqueeGroup customClass="bg-black" textClass="text-white" />
</section>

<About />

<Project />

<Advantage />

<Accolades />

<Testimonial />

<Blog />

<Cta />
