// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Marketing3/components/Hero.tsx
import marketing1 from '@/assets/images/landing/marketing-3/img-1.jpg'
import { LuMoveRight } from 'react-icons/lu'
import { Link } from 'react-router-dom'

const Hero = () => {
  return (
    <section id="home" className="relative overflow-hidden">
      <div className="px-4 md:px-10">
        <div className="overflow-hidden rounded-2xl bg-cover bg-center bg-no-repeat" style={{ backgroundImage: `url(${marketing1})` }}>
          <div className="rounded-2xl bg-black/60">
            <div className="container">
              <div className="relative p-6">
                <div className="flex h-full items-center justify-center py-36">
                  <div className="relative mx-auto max-w-3xl text-center">
                    <span className="rounded-md bg-white/10 px-3 py-1 text-sm font-medium uppercase tracking-wider text-white">AI knowledge hub</span>
                    <h1 className="mt-10 text-3xl font-medium text-white md:text-5xl/snug">
                      Build Quickly, Earn More
                    </h1>
                    <p className="mx-auto mt-5 w-3/4 text-base text-white/80">
                      Leverage customer data to create exceptional and robust
                      product experiences that drive conversions.
                    </p>
                    <div className="mt-10 flex justify-center">
                      <Link to="" className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-8 py-2 text-base text-white transition-all duration-300 hover:bg-primary-700">Read More
                        <LuMoveRight className="h-6 w-6" />
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Hero

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/marketing-3/Hero.svelte
<script lang="ts">
	import { MoveRightIcon } from 'lucide-svelte';
	import { marketing3Img1 } from '$lib/utilities/images';
</script>

<section id="home" class="relative overflow-hidden">
	<div class="px-4 md:px-10">
		<div
			class="overflow-hidden rounded-2xl bg-cover bg-center bg-no-repeat"
			style={`background-image:url(${marketing3Img1})`}>
			<div class="rounded-2xl bg-black/60">
				<div class="container">
					<div class="relative p-6">
						<div class="flex h-full items-center justify-center py-36">
							<div class="relative mx-auto max-w-3xl text-center">
                    <span
											class="rounded-md bg-white/10 px-3 py-1 text-sm font-medium uppercase tracking-wider text-white"
										>AI knowledge hub</span>
								<h1
									class="mt-10 text-3xl font-medium text-white md:text-5xl/snug">
									Build Quickly, Earn More
								</h1>
								<p class="mx-auto mt-5 w-3/4 text-base text-white/80">
									Leverage customer data to create exceptional and robust
									product experiences that drive conversions.
								</p>

								<div class="mt-10 flex justify-center">
									<a
										href={null}
										class="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-8 py-2 text-base text-white transition-all duration-300 hover:bg-primary-700"
									>Read More
										<MoveRightIcon class="h-6 w-6" />
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
