// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/hosting/index.vue
<template>
  <Navbar1
    menu-position="fixed"
    :navbar-link="navLinkData"
    btn-text="Download"
    :btn-icon="DownloadCloudIcon"
  />

  <HostingHero />

  <Brands :brand-data="brandData" />

  <Pricing />

  <Service />

  <Cta />

  <Feature />

  <Testimonial />

  <Faq />

  <Extra />

  <Footer />

  <client-only>
    <BackToTop />
  </client-only>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

import Navbar1 from '@/layouts/partials/Navbar1.vue'
import HostingHero from '@/components/heros/HostingHero.vue'
import Brands from '@/components/sections/Brands.vue'
import Pricing from '@/pages/landings/hosting/components/Pricing.vue'
import Service from '@/pages/landings/hosting/components/Service.vue'
import Cta from '@/pages/landings/hosting/components/Cta.vue'
import Feature from '@/pages/landings/hosting/components/Feature.vue'
import Testimonial from '@/pages/landings/hosting/components/Testimonial.vue'
import Faq from '@/pages/landings/hosting/components/Faq.vue'
import Extra from '@/pages/landings/hosting/components/Extra.vue'
import Footer from '@/layouts/partials/Footer.vue'
import BackToTop from '@/layouts/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

import { brandData } from '@/utilities/common'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home'
  },
  {
    id: 'pricing',
    name: 'Pricing'
  },
  {
    id: 'services',
    name: 'Services'
  },
  {
    id: 'features',
    name: 'Features'
  },
  {
    id: 'testimonial',
    name: 'Testimonial'
  },
  {
    id: 'faq',
    name: 'Faq'
  }
]
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/hosting/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import Brands from '$lib/components/sections/Brands.svelte';
	import { brandData } from '$lib/utilities/common';
	import Pricing from './Pricing.svelte';
	import Service from './Service.svelte';
	import Cta from './Cta.svelte';
	import Feature from './Feature.svelte';
	import Testimonial from './Testimonial.svelte';
	import Faq from './Faq.svelte';
	import Extra from './Extra.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'pricing',
			name: 'Pricing'
		},
		{
			id: 'services',
			name: 'Services'
		},
		{
			id: 'features',
			name: 'Features'
		},
		{
			id: 'testimonial',
			name: 'Testimonial'
		},
		{
			id: 'faq',
			name: 'Faq'
		}
	];
</script>


<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<Brands brandData={brandData} />

<Pricing />

<Service />

<Cta />

<Feature />

<Testimonial />

<Faq />

<Extra />
