// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/home/footer/footer.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [LucideAngularModule],
  template: `<footer class="relative border-t border-default-200">
    <div class="container relative">
      <p class="py-6 text-center font-medium text-default-900">
        {{ year }}
        © AeroPage. Crafted and Coded with
        <span class="text-red-500">❤️</span> by
        <a
          class="text-primary-700"
          href="https://coderthemes.com/"
          target="_blank"
          >Coderthemes</a
        >
      </p>
    </div>
  </footer>`,
  styles: ``,
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
})
export class FooterComponent {
  year = new Date().getFullYear()
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/layouts/AdminLayout/components/Footer.tsx
import { Link } from "react-router-dom"

const Footer = () => {
  return (
    <footer className="w-full border-t border-default-200 bg-white py-4 dark:bg-default-50">
      <div className="container">
        <div className="grid items-center gap-6 lg:grid-cols-2">
          <p className="text-center text-default-900 lg:text-start">
            {new Date().getFullYear()} © AeroPage. Crafted and Coded with&nbsp;
            <span className="text-red-500">❤️</span> by&nbsp;
            <Link className="text-primary-700" to="https://coderthemes.com/" target="_blank">Coderthemes</Link>
          </p>
          <div className="hidden justify-center gap-6 text-center lg:flex lg:justify-end">
            <Link to="" className="font-medium text-default-500">
              Terms
            </Link>
            <Link to="" className="font-medium text-default-500">
              Privacy
            </Link>
            <Link to="" className="font-medium text-default-500">
              Cookies
            </Link>
          </div>
        </div>
      </div>
    </footer>

  )
}

export default Footer
