// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/marketing-3/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar2 from '$lib/components/layouts/Navbar2.svelte';
	import Hero from './Hero.svelte';
	import Solution from './Solution.svelte';
	import Project from './Project.svelte';
	import Feature from './Feature.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import Faq from './Faq.svelte';
	import Cta from './Cta.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'solutions',
			name: 'Solutions'
		},
		{
			id: 'projects',
			name: 'Projects'
		},
		{
			id: 'features',
			name: 'Features'
		},
		{
			id: 'faq',
			name: 'Faq'
		}
	];
</script>


<Navbar2 menuPosition="sticky" navbarLink={navLinkData} />

<Hero />

<Solution />

<Project />

<Feature />

<section class="pb-10 pt-20">
	<MarqueeGroup marqeeItems={['eCommerce','Development','Social media','Consultation']}
								customClass="gap-10 border-y py-8"
								textClass="text-5xl font-medium text-default-950" />
</section>

<Faq />

<Cta />

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/marketing-3/index.vue
<template>
  <Navbar2
    menu-position="sticky"
    :navbar-link="navLinkData"
    btn-text="Download"
    :btn-icon="DownloadCloudIcon"
  />

  <Marketing3Hero />

  <Solution />

  <Project />

  <Feature />

  <section class="pb-10 pt-20">
    <MarqueeGroup
      :marqee-items="['eCommerce', 'Development', 'Social media', 'Consultation']"
      custom-class="gap-10 border-y py-8"
      text-class="text-5xl font-medium text-default-950"
    />
  </section>

  <Faq />

  <Cta />

  <Footer />

  <client-only>
    <BackToTop />
  </client-only>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

import Navbar2 from '@/layouts/partials/Navbar2.vue'
import Marketing3Hero from '@/components/heros/Marketing3Hero.vue'
import Solution from '@/pages/landings/marketing-3/components/Solution.vue'
import Project from '@/pages/landings/marketing-3/components/Project.vue'
import Feature from '@/pages/landings/marketing-3/components/Feature.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import Faq from '@/pages/landings/marketing-3/components/Faq.vue'
import Cta from '@/pages/landings/marketing-3/components/Cta.vue'
import Footer from '@/layouts/partials/Footer.vue'
import BackToTop from '@/layouts/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home'
  },
  {
    id: 'solutions',
    name: 'Solutions'
  },
  {
    id: 'projects',
    name: 'Projects'
  },
  {
    id: 'features',
    name: 'Features'
  },
  {
    id: 'faq',
    name: 'Faq'
  }
]
</script>
