// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/admin/chat/+page.svelte
<script lang="ts">
	import AdminPageTitle from '$lib/components/layouts/AdminPageTitle.svelte';
	import ContactList from './ContactList.svelte';
	import Chat from './Chat.svelte';
</script>

<AdminPageTitle title="Chat" subtitle="Admin" />

<section>
	<div class="container">
		<div class="my-6 space-y-6">
			<div class="grid gap-4 lg:grid-cols-3">
				<div class="lg:col-span-1">
					<ContactList />
				</div>

				<div class="lg:col-span-2">
					<Chat />
				</div>
			</div>
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/admin/chat/index.vue
<template>
  <AdminPageTitle title="Chat" subtitle="Admin" />

  <section>
    <div class="container">
      <div class="my-6 space-y-6">
        <div class="grid gap-4 lg:grid-cols-3">
          <div class="lg:col-span-1">
            <ContactList />
          </div>

          <div class="lg:col-span-2">
            <Chat />
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'admin'
})

import AdminPageTitle from '@/layouts/partials/AdminPageTitle.vue'
import ContactList from '@/pages/admin/chat/components/ContactList.vue'
import Chat from '@/pages/admin/chat/components/Chat.vue'
</script>
