// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Charity/components/Blog.jsx
import { LuMoveRight } from "react-icons/lu";
import { Link } from "react-router-dom";

import charity8 from "@/assets/images/landing/charity/img-8.png";
import charityBackground3 from "@/assets/images/landing/charity/bg-3.png";
import charityBackground4 from "@/assets/images/landing/charity/bg-4.png";
import charityBackground5 from "@/assets/images/landing/charity/bg-5.png";

const Blog = () => {
  return (
    <section id="blog" className="py-10 lg:pb-20">
      <div className="container">
        <div className="grid items-center gap-6 lg:grid-cols-2">
          <div>
            <span className="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary">
              How You Can Make a Difference
            </span>
            <h2 className="mt-4 text-4xl/snug font-medium text-default-950">
              It's incredibly straightforward.
            </h2>
            <p className="mt-5 text-base">
              Children growing up in poverty encounter significant challenges:
              hunger and malnutrition, restricted access to education and
              healthcare, social discrimination, and isolation.
            </p>
            <div className="mt-10">
              <Link
                to=""
                className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-8 py-2 text-base text-white transition-all hover:bg-primary-700"
              >
                Read More
                <LuMoveRight className="h-6 w-6" />
              </Link>
            </div>
          </div>
          <div>
            <div className="choose-image relative">
              <img src={charity8} alt="image" />
              <div className="choose-image-shape hidden md:block">
                <div className="absolute left-0 top-0 z-10 animate-[moveLeftBounce_3s_linear_infinite]">
                  <img src={charityBackground3} alt="image" />
                </div>
                <div className="absolute right-[-10%] top-2/4 -z-10 hidden -translate-y-2/4 animate-[moveLeftBounce_3s_linear_infinite] lg:block">
                  <img src={charityBackground4} alt="image" />
                </div>
                <div className="absolute bottom-[10%] left-[12%] -z-10 animate-[moveLeftBounce_3s_linear_infinite]">
                  <img src={charityBackground5} alt="image" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Blog;

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/charity/components/Blog.vue
<template>
  <section id="blog" class="py-10 lg:pb-20">
    <div class="container">
      <div class="grid lg:grid-cols-2 gap-6 items-center">
        <div>
          <span
            class="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary"
            >How You Can Make a Difference</span
          >
          <h2 class="text-4xl/snug font-medium text-default-950 mt-4">
            It's incredibly straightforward.
          </h2>
          <p class="text-base mt-5">
            Children growing up in poverty encounter significant challenges: hunger and
            malnutrition, restricted access to education and healthcare, social discrimination, and
            isolation.
          </p>
          <div class="mt-10">
            <a
              href="#"
              class="inline-flex items-center justify-center gap-2 text-base py-2 px-8 rounded-md text-white bg-primary hover:bg-primary-700 transition-all"
              >Read More
              <MoveRightIcon class="h-6 w-6" />
            </a>
          </div>
        </div>

        <div>
          <div class="choose-image relative">
            <img :src="charityImg8" alt="image" />

            <div class="choose-image-shape md:block hidden">
              <div class="absolute z-10 animate-[moveLeftBounce_3s_linear_infinite] left-0 top-0">
                <img :src="charityImg3" alt="image" />
              </div>
              <div
                class="absolute right-[-10%] -translate-y-2/4 -z-10 animate-[moveLeftBounce_3s_linear_infinite] top-2/4"
              >
                <img :src="charityImg4" alt="image" />
              </div>
              <div
                class="absolute -z-10 animate-[moveLeftBounce_3s_linear_infinite] left-[12%] bottom-[10%]"
              >
                <img :src="charityImg5" alt="image" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { MoveRightIcon } from 'lucide-vue-next'
import charityImg3 from 'assets/images/landing/charity/bg-3.png'
import charityImg4 from 'assets/images/landing/charity/bg-4.png'
import charityImg5 from 'assets/images/landing/charity/bg-5.png'
import charityImg8 from 'assets/images/landing/charity/img-8.png'
</script>
