// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/charity/contact.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [],
  template: `
    <section id="contact" class="py-10 lg:py-20">
      <div class="container">
        <div class="relative z-20">
          <div class="hidden xl:block">
            <div
              class="before:absolute before:-end-10 before:-top-10 before:-z-10 before:h-24 before:w-24 before:bg-[url('../images/other/dot.svg')]"
            ></div>
            <div
              class="after:absolute after:-bottom-10 after:-start-10 after:-z-10 after:h-24 after:w-24 after:bg-[url('../images/other/dot.svg')]"
            ></div>
          </div>

          <div class="grid gap-6 xl:grid-cols-2">
            <div class="group relative">
              <img
                src="assets/images/landing/charity/img-11.jpg"
                class="h-full w-full rounded-xl"
                alt=""
              />
              <div class="absolute inset-0 rounded-xl">
                <div class="flex h-full items-end justify-center">
                  <div
                    class="m-6 mx-auto max-w-md rounded-xl bg-white/10 p-4 text-center backdrop-blur-xl"
                  >
                    <h2 class="text-4xl/snug font-medium text-white">
                      Would you like to support our mission?
                    </h2>
                    <p class="mt-5 text-base text-white/80">
                      Complete the form and become a part of our community.
                    </p>
                  </div>
                </div>
                <!-- flex  End -->
              </div>
            </div>
            <!-- col End -->

            <div>
              <div class="rounded-md bg-default-100 p-8 dark:bg-default-50">
                <form class="relative">
                  <h2 class="text-2xl font-medium text-default-950">
                    Join Us Today!
                  </h2>
                  <div class="my-6 space-y-6">
                    <div>
                      <input
                        type="text"
                        class="block w-full rounded-full border-default-200 px-4 py-3 text-base text-default-950 focus:border-default-300 focus:ring-transparent dark:bg-default-50"
                        id="formFirstName"
                        placeholder="Your first name..."
                        required=""
                      />
                    </div>
                    <!-- col End -->

                    <div>
                      <input
                        type="email"
                        class="block w-full rounded-full border-default-200 px-4 py-3 text-base text-default-950 focus:border-default-300 focus:ring-transparent dark:bg-default-50"
                        id="formEmail"
                        placeholder="Your email..."
                        required=""
                      />
                    </div>
                    <!-- col End -->

                    <div>
                      <input
                        type="text"
                        class="block w-full rounded-full border-default-200 px-4 py-3 text-base text-default-950 focus:border-default-300 focus:ring-transparent dark:bg-default-50"
                        id="formSubject"
                        placeholder="Studying Class"
                        required=""
                      />
                    </div>
                    <!-- col End -->

                    <div>
                      <input
                        type="text"
                        class="block w-full rounded-full border-default-200 px-4 py-3 text-base text-default-950 focus:border-default-300 focus:ring-transparent dark:bg-default-50"
                        id="formSubject"
                        placeholder="Type Your Requirements"
                        required=""
                      />
                    </div>
                    <!-- col End -->
                  </div>
                  <!-- grid End -->

                  <button
                    type="submit"
                    class="flex w-full items-center justify-center rounded-full bg-primary py-3 text-base text-white transition-all hover:bg-primary-700"
                  >
                    Submit Now
                  </button>
                </form>
                <!-- From End -->
              </div>
            </div>
            <!-- col End -->
          </div>
          <!-- grid End -->
        </div>
      </div>
      <!-- Container End -->
    </section>
  `,
  styles: ``,
})
export class ContactComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/charity/components/Contact.vue
<template>
  <section id="contact" class="py-10 lg:py-20">
    <div class="container">
      <div class="relative z-20">
        <div class="hidden xl:block">
          <div
            class="before:w-24 before:h-24 before:absolute before:-top-10 before:-end-10 before:-z-10 before:bg-[url('../images/other/dot.svg')]"
          ></div>
          <div
            class="after:w-24 after:h-24 after:absolute after:-bottom-10 after:-start-10 after:-z-10 after:bg-[url('../images/other/dot.svg')]"
          ></div>
        </div>

        <div class="grid xl:grid-cols-2 gap-6">
          <div class="relative group">
            <img :src="charityImg11" class="h-full w-full rounded-xl" alt="" />
            <div class="absolute inset-0 rounded-xl">
              <div class="flex items-end justify-center h-full">
                <div
                  class="max-w-md mx-auto text-center bg-white/10 backdrop-blur-xl p-4 m-6 rounded-xl"
                >
                  <h2 class="text-4xl/snug font-medium text-white">
                    Would you like to support our mission?
                  </h2>
                  <p class="text-base text-white/80 mt-5">
                    Complete the form and become a part of our community.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div>
            <div class="p-8 rounded-md bg-default-100 dark:bg-default-50">
              <form class="relative">
                <h2 class="text-2xl font-medium text-default-950">Join Us Today!</h2>
                <div class="space-y-6 my-6">
                  <div>
                    <input
                      type="text"
                      class="py-3 px-4 block w-full text-base rounded-full text-default-950 border-default-200 dark:bg-default-50 focus:border-default-300 focus:ring-transparent"
                      id="formFirstName"
                      placeholder="Your first name..."
                      required
                    />
                  </div>

                  <div>
                    <input
                      type="email"
                      class="py-3 px-4 block w-full text-base rounded-full text-default-950 border-default-200 dark:bg-default-50 focus:border-default-300 focus:ring-transparent"
                      id="formEmail"
                      placeholder="Your email..."
                      required
                    />
                  </div>

                  <div>
                    <input
                      type="text"
                      class="py-3 px-4 block w-full text-base rounded-full text-default-950 border-default-200 dark:bg-default-50 focus:border-default-300 focus:ring-transparent"
                      id="formSubject"
                      placeholder="Studying Class"
                      required
                    />
                  </div>

                  <div>
                    <input
                      type="text"
                      class="py-3 px-4 block w-full text-base rounded-full text-default-950 border-default-200 dark:bg-default-50 focus:border-default-300 focus:ring-transparent"
                      id="formSubject"
                      placeholder="Type Your Requirements"
                      required
                    />
                  </div>
                </div>

                <button
                  type="submit"
                  class="py-3 w-full flex items-center justify-center rounded-full text-base text-white bg-primary hover:bg-primary-700 transition-all"
                >
                  Submit Now
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import charityImg11 from 'assets/images/landing/charity/img-11.jpg'
</script>
