// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/charity/join.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'
import { VideoPlayerComponent } from '@components/video-player.component'

@Component({
  selector: 'app-join',
  standalone: true,
  imports: [LucideAngularModule, VideoPlayerComponent],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],

  template: `
    <section id="join" class="py-10 lg:py-20">
      <div class="container">
        <div class="mx-auto max-w-2xl text-center">
          <span
            class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
            >Starting with a Child</span
          >
          <h2 class="mt-4 text-3xl/snug font-medium text-default-950">
            Starting with a Child
          </h2>
          <p class="mt-5 text-base">
            Children growing up in poverty encounter significant challenges
            education and healthcare, social discrimination, and isolation.
          </p>
        </div>

        <div class="mt-10">
          <div class="grid grid-cols-3 gap-6">
            <div class="col-span-2">
              <div class="group relative h-full">
                <img
                  src="assets/images/landing/charity/img-4.jpg"
                  class="h-full w-full rounded-xl"
                  alt=""
                />

                <div
                  class="opacity-0 transition-all duration-700 group-hover:opacity-100"
                >
                  <div
                    class="absolute inset-0 flex h-full items-center justify-center rounded-xl bg-black/50"
                  >
                    <button
                      class="relative flex h-20 w-20 items-center justify-center gap-2.5 rounded-full bg-primary text-base font-medium text-default-950 ring-4 ring-primary/25 transition-all duration-300 hover:bg-primary"
                      data-hs-overlay="#watchvideomodal"
                    >
                      <lucide-angular
                        name="play"
                        class="size-7 fill-white stroke-white"
                      ></lucide-angular>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <!-- col-span-2 End -->

            <div class="space-y-5">
              <div class="group relative">
                <img
                  src="assets/images/landing/charity/img-5.jpg"
                  class="rounded-xl"
                  alt=""
                />

                <div
                  class="opacity-0 transition-all duration-700 group-hover:opacity-100"
                >
                  <div
                    class="absolute inset-0 flex h-full items-center justify-center rounded-xl bg-black/50"
                  >
                    <button
                      class="relative flex size-14 items-center justify-center gap-2.5 rounded-full bg-primary text-base font-medium text-default-950 ring-4 ring-primary/25 transition-all duration-300 hover:bg-primary"
                      data-hs-overlay="#watchvideomodal"
                    >
                      <lucide-angular
                        name="play"
                        class="size-5 fill-white stroke-white"
                      ></lucide-angular>
                    </button>
                  </div>
                </div>
              </div>
              <!-- col End -->

              <div class="group relative">
                <img
                  src="assets/images/landing/charity/img-2.jpg"
                  class="rounded-xl"
                  alt=""
                />

                <div
                  class="opacity-0 transition-all duration-700 group-hover:opacity-100"
                >
                  <div
                    class="absolute inset-0 flex h-full items-center justify-center rounded-xl bg-black/50"
                  >
                    <button
                      class="relative flex size-14 items-center justify-center gap-2.5 rounded-full bg-primary text-base font-medium text-default-950 ring-4 ring-primary/25 transition-all duration-300 hover:bg-primary"
                      data-hs-overlay="#watchvideomodal"
                    >
                      <lucide-angular
                        name="play"
                        class="size-5 fill-white stroke-white"
                      ></lucide-angular>
                    </button>
                  </div>
                </div>
              </div>
              <!-- col End -->
            </div>
            <!-- col End -->
          </div>
          <!-- grid End -->
        </div>
      </div>
      <!-- Container End -->
    </section>

    <!-- Watch Video Modal Start -->
    <div
      id="watchvideomodal"
      class="hs-overlay pointer-events-none fixed start-0 top-0 z-[80] hidden h-full w-full overflow-y-auto overflow-x-hidden"
    >
      <div
        class="m-3 mt-0 flex min-h-[calc(100%-3.5rem)] items-center opacity-0 transition-all ease-out hs-overlay-open:mt-7 hs-overlay-open:opacity-100 hs-overlay-open:duration-500 sm:mx-auto sm:w-full sm:max-w-xl"
      >
        <div
          class="pointer-events-auto flex w-full flex-col overflow-x-hidden rounded-xl"
        >
          <iframe
            class="w-full"
            height="400"
            src="https://www.youtube.com/embed/NbR-wVOpJwA?si=OlR2e-UItbGilVlu"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen
          ></iframe>
        </div>
      </div>
    </div>
    <!-- Watch Video Modal End -->
  `,
  styles: ``,
})
export class JoinComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/charity/components/Join.vue
<template>
  <section id="join" class="py-10 lg:py-20">
    <div class="container">
      <div class="max-w-2xl mx-auto text-center">
        <span
          class="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary"
          >Starting with a Child</span
        >
        <h2 class="text-3xl/snug font-medium text-default-950 mt-4">
          Starting with a Child - Join Us.
        </h2>
        <p class="text-base mt-5">
          Children growing up in poverty encounter significant challenges education and healthcare,
          social discrimination, and isolation.
        </p>
      </div>

      <div class="mt-10">
        <div class="grid grid-cols-3 gap-6">
          <div class="col-span-2">
            <div class="relative h-full group">
              <img :src="charity4" class="h-full w-full rounded-xl" alt="" />

              <div class="opacity-0 group-hover:opacity-100 transition-all duration-700">
                <div
                  class="absolute inset-0 rounded-xl bg-black/50 flex items-center justify-center h-full"
                >
                  <button
                    class="relative h-20 w-20 flex items-center justify-center gap-2.5 rounded-full text-base font-medium bg-primary text-default-950 transition-all duration-300 ring-4 ring-primary/25 hover:bg-primary"
                    data-hs-overlay="#watchvideomodal"
                  >
                    <PlayIcon class="h-7 w-7 stroke-white fill-white" />
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div class="space-y-5">
            <div class="relative group">
              <img :src="charity5" class="rounded-xl" alt="" />

              <div class="opacity-0 group-hover:opacity-100 transition-all duration-700">
                <div
                  class="absolute inset-0 rounded-xl bg-black/50 flex items-center justify-center h-full"
                >
                  <button
                    class="relative h-14 w-14 flex items-center justify-center gap-2.5 rounded-full text-base font-medium bg-primary text-default-950 transition-all duration-300 ring-4 ring-primary/25 hover:bg-primary"
                    data-hs-overlay="#watchvideomodal"
                  >
                    <PlayIcon class="h-5 w-5 stroke-white fill-white" />
                  </button>
                </div>
              </div>
            </div>

            <div class="relative group">
              <img :src="charity2" class="rounded-xl" alt="" />

              <div class="opacity-0 group-hover:opacity-100 transition-all duration-700">
                <div
                  class="absolute inset-0 rounded-xl bg-black/50 flex items-center justify-center h-full"
                >
                  <button
                    class="relative h-14 w-14 flex items-center justify-center gap-2.5 rounded-full text-base font-medium bg-primary text-default-950 transition-all duration-300 ring-4 ring-primary/25 hover:bg-primary"
                    data-hs-overlay="#watchvideomodal"
                  >
                    <PlayIcon class="h-5 w-5 stroke-white fill-white" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Watch Video Modal Start -->
  <div
    id="watchvideomodal"
    class="hs-overlay hidden w-full h-full fixed top-0 start-0 z-[80] overflow-x-hidden overflow-y-auto pointer-events-none"
  >
    <div
      class="hs-overlay-open:mt-7 hs-overlay-open:opacity-100 hs-overlay-open:duration-500 mt-0 opacity-0 ease-out transition-all sm:max-w-xl sm:w-full m-3 sm:mx-auto min-h-[calc(100%-3.5rem)] flex items-center"
    >
      <div class="w-full flex flex-col pointer-events-auto rounded-xl overflow-x-hidden">
        <iframe
          class="w-full"
          height="400"
          src="https://www.youtube.com/embed/NbR-wVOpJwA?si=OlR2e-UItbGilVlu"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
        ></iframe>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import charity2 from 'assets/images/landing/charity/img-2.jpg'
import charity4 from 'assets/images/landing/charity/img-4.jpg'
import charity5 from 'assets/images/landing/charity/img-5.jpg'
import { PlayIcon } from 'lucide-vue-next'
</script>
