// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/photography/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar2 from '$lib/components/layouts/Navbar2.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import About from './About.svelte';
	import Service from './Service.svelte';
	import Portfolio from './Portfolio.svelte';
	import Faq from './Faq.svelte';
	import Blog from './Blog.svelte';
	import Contact from './Contact.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'services',
			name: 'Services'
		},
		{
			id: 'portfolio',
			name: 'Portfolio'
		},
		{
			id: 'faq',
			name: 'Faq'
		}
	];
</script>

<Navbar2 menuPosition="sticky" navbarLink={navLinkData} />

<Hero />

<section>
	<MarqueeGroup
		marqeeItems={['Wildlife photography','Pet portraits','Nature photography','Wildlife photography','Pet portraits','Nature photography']}
		customClass="relative m-auto flex gap-28 overflow-hidden bg-black py-6"
		textClass="text-4xl text-white"
	/>
</section>

<About />

<Service />

<Portfolio />

<Faq />

<Blog />

<Contact />

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/photography/photography.component.ts
import { Component } from '@angular/core'
import { HeaderComponent } from '@components/header/header.component'
import { HeroComponent } from './hero.component'
import { AboutComponent } from './about.component'
import { ServicesComponent } from './services.component'
import { PortfolioComponent } from './portfolio.component'
import { FaqComponent } from './faq.component'
import { LatestUpdatesComponent } from './latest-updates.component'
import { AdventureComponent } from './adventure.component'
import { MarqueeComponent } from '@components/marquee/marquee.component'

@Component({
  selector: 'app-photography',
  standalone: true,
  imports: [
    HeaderComponent,
    HeroComponent,
    MarqueeComponent,
    AboutComponent,
    ServicesComponent,
    PortfolioComponent,
    FaqComponent,
    LatestUpdatesComponent,
    AdventureComponent,
  ],
  template: `
    <app-header
      [customLinks]="photographyLinks"
      [className]="'sticky'"
      [sidebarNav]="false"
    />
    <!-- hero component -->
    <app-hero />
    <!-- marquee -->
    <section>
      <app-marquee
        [marqueeContent]="marqueeContent"
        [customClass]="customClass"
        [childClass]="childClass"
        [parentClass]="parentClass"
      />
    </section>
    <!-- about -->
    <app-about />
    <!-- services -->
    <app-services />
    <!-- portfolio -->
    <app-portfolio />
    <!-- faq  -->
    <app-faq />
    <!-- latest updates -->
    <app-latest-updates />
    <!-- Adventure -->
    <app-adventure />
    <!-- marquee -->
    <section>
      <app-marquee
        [marqueeContent]="marqueeContent"
        [customClass]="customClass"
        [childClass]="childClass"
        [parentClass]="parentClass"
      />
    </section>
  `,
  styles: ``,
})
export class PhotographyComponent {
  photographyLinks = [
    { label: 'Home', route: 'home' },
    { label: 'About ', route: 'about' },
    { label: 'Services', route: 'services' },
    { label: 'Portfolio', route: 'portfolio' },
    { label: 'Faq', route: 'faq' },
  ]

  marqueeContent: string[] = [
    'Wildlife photography',
    'Pet portraits',
    'Nature photography ',
    'Pet portraits',
    'Nature photography',
  ]
  customClass = 'text-4xl text-white'
  childClass = 'gap-28 py-6'
  parentClass = 'gap-28 bg-black'
}
