// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/portfolio-2/About.svelte
<script lang="ts">
	import { MoveRightIcon } from 'lucide-svelte';
	import { avatar1 } from '$lib/utilities/images';
</script>

<section id="about" class="py-10 lg:py-20">
	<div class="container">
		<div class="grid items-center gap-6 xl:grid-cols-5">
			<div class="xl:col-span-2">
				<div>
					<img
						src={avatar1}
						class="mx-auto h-80 rounded-full"
						alt="" />
				</div>
			</div>

			<div class="xl:col-span-3">
            <span
							class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
						>Our About</span>
				<h2 class="mt-4 text-4xl font-medium text-default-950">
					Entrepreneur of the Year
				</h2>
				<h4 class="mt-5 text-xl font-medium text-default-400">
					Hello! I'm Diego, a self-taught and award-winning Digital Designer
					and Developer with more than fifteen years of professional
					experience. I began my journey in my childhood bedroom and honed
					my skills at renowned digital agencies like nexum AG.
				</h4>

				<div class="mt-6 flex flex-wrap items-center gap-6">
					<div
						class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
						<h2 class="text-4xl font-medium text-default-950">200+</h2>
						<p class="mt-2 text-base">Project Delivered</p>
					</div>

					<div
						class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
						<h2 class="text-4xl font-medium text-default-950">20+</h2>
						<p class="mt-2 text-base">Years of Experience</p>
					</div>

					<div
						class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
						<h2 class="text-4xl font-medium text-default-950">45+</h2>
						<p class="mt-2 text-base">Happy Clients</p>
					</div>
				</div>
				<div class="inline-block">
					<a
						href={null}
						class="mt-6 flex items-center justify-center gap-2 rounded-md border border-primary bg-primary/90 px-6 py-2 text-lg text-white transition-all hover:bg-primary"
					>Read more
						<MoveRightIcon class="h-7 w-7" />
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/portfolio-2/components/About.vue
<template>
  <section id="about" class="py-10 lg:py-20">
    <div class="container">
      <div class="grid items-center gap-6 xl:grid-cols-5">
        <div class="xl:col-span-2">
          <div>
            <img :src="avatar1" class="mx-auto h-80 rounded-full" alt="" />
          </div>
        </div>

        <div class="xl:col-span-3">
          <span
            class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
            >Our About</span
          >
          <h2 class="mt-4 text-4xl font-medium text-default-950">Entrepreneur of the Year</h2>
          <h4 class="mt-5 text-xl font-medium text-default-400">
            Hello! I'm Diego, a self-taught and award-winning Digital Designer and Developer with
            more than fifteen years of professional experience. I began my journey in my childhood
            bedroom and honed my skills at renowned digital agencies like nexum AG.
          </h4>

          <div class="mt-6 flex flex-wrap items-center gap-6">
            <div class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
              <h2 class="text-4xl font-medium text-default-950">200+</h2>
              <p class="mt-2 text-base">Project Delivered</p>
            </div>

            <div class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
              <h2 class="text-4xl font-medium text-default-950">20+</h2>
              <p class="mt-2 text-base">Years of Experience</p>
            </div>

            <div class="w-48 rounded-xl bg-white p-4 text-center drop-shadow-md dark:bg-default-50">
              <h2 class="text-4xl font-medium text-default-950">45+</h2>
              <p class="mt-2 text-base">Happy Clients</p>
            </div>
          </div>
          <div class="inline-block">
            <a
              href="#"
              class="mt-6 flex items-center justify-center gap-2 rounded-md border border-primary bg-primary/90 px-6 py-2 text-lg text-white transition-all hover:bg-primary"
              >Read more
              <MoveRightIcon class="h-7 w-7" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import avatar1 from '@/assets/images/avatars/img-1.jpg'
import { MoveRightIcon } from 'lucide-vue-next'
</script>
