// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/portfolio-2/Cta.svelte
<script lang="ts">
	import { MoveRightIcon } from 'lucide-svelte';
</script>

<section class="bg-default-100 py-10 lg:py-20">
	<div class="container">
		<div class="mx-auto text-center">
			<h2
				class="mt-5 text-3xl font-medium text-default-950 md:text-4xl/tight">
				Let's Explore the Next Major Innovation
			</h2>
			<p class="mt-6 text-base text-default-950">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
				ad minim veniam, quis nostrud exercitation ullamco laboris.
			</p>
			<div class="mt-7 flex flex-wrap items-center justify-center gap-6">
				<a
					href={null}
					class="flex items-center justify-center gap-2 rounded-lg bg-primary/90 px-8 py-3 text-lg text-white transition-all hover:bg-primary"
				>Write A Message
					<MoveRightIcon class="h-7 w-7" />
				</a>
				<a
					href={null}
					class="flex items-center justify-center gap-2 rounded-lg bg-black px-8 py-3 text-lg text-white transition-all"
				>Discuss Project
					<MoveRightIcon class="h-7 w-7" />
				</a>
			</div>
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/portfolio-2/components/Cta.vue
<template>
  <section class="bg-default-100 py-10 lg:py-20">
    <div class="container">
      <div class="mx-auto text-center">
        <h2 class="mt-5 text-3xl font-medium text-default-950 md:text-4xl/tight">
          Let's Explore the Next Major Innovation
        </h2>
        <p class="mt-6 text-base text-default-950">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          ullamco laboris.
        </p>
        <div class="mt-7 flex flex-wrap items-center justify-center gap-6">
          <a
            href="#"
            class="flex items-center justify-center gap-2 rounded-lg bg-primary/90 px-8 py-3 text-lg text-white transition-all hover:bg-primary"
            >Write A Message
            <MoveRightIcon class="h-7 w-7" />
          </a>
          <a
            href="#"
            class="flex items-center justify-center gap-2 rounded-lg bg-black px-8 py-3 text-lg text-white transition-all"
            >Discuss Project
            <MoveRightIcon class="h-7 w-7" />
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { MoveRightIcon } from 'lucide-vue-next'
</script>
