// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/marketing-2/Service.svelte
<script lang="ts">
	import { BoxIcon, DotIcon, FileTextIcon, MoveRightIcon, RocketIcon } from 'lucide-svelte';
</script>

<section id="services" class="py-10 lg:py-20">
	<div class="container">
		<div class="mx-auto mb-14 max-w-xl text-center">
          <span
						class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
					>Our Services</span>
			<h2 class="mt-4 text-4xl/tight font-medium text-default-950">
				Marketing Solutions
			</h2>
			<p class="mt-5 text-base">
				The marketing mix symbolizes the fundamental instruments that
				marketers can employ to introduce their products or services to the
				market.
			</p>
		</div>

		<div class="border border-default-200">
			<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3">
				<div class="border-b border-default-200 p-6 md:border-e xl:border-0">
					<div class="mx-auto">
						<FileTextIcon class="inline-block h-12 w-12 text-default-950" />
					</div>
					<h2 class="mt-5 text-2xl font-medium text-default-950">
						Media Relations
					</h2>
					<p class="mt-5 text-base">
						Price need not be exclusively monetary; it can also encompass
						what is traded for the product or services, including energy or
						any sacrifices consumers make to acquire them.
					</p>

					<ul
						role="list"
						class="text-default-white -ms-3 mb-3 mt-4 text-sm">
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950"
							>Seasonal Campaigns</span
							>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950"
							>Digital Marketing</span
							>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Sponsorships</span>
						</li>
					</ul>


					<a href={null}
						 class="group text-lg font-medium text-default-950"
					>Read More
						<MoveRightIcon
							class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100" />
					</a>
				</div>

				<div class="border-b border-default-200 p-6 xl:border-x xl:border-b-0">
					<div class="mx-auto">
						<BoxIcon class="inline-block h-12 w-12 text-default-950" />
					</div>
					<h2 class="mt-5 text-2xl font-medium text-default-950">
						Marketing Consultancy
					</h2>
					<p class="mt-5 text-base">
						The product facets of marketing involve the specifications of
						the relevant products, goods, or services, and their alignment
						with the needs and desires of the end-users.
					</p>

					<ul role="list"
							class="text-default-white -ms-3 mb-3 mt-4 text-sm">
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Search Engine Optimization</span>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Strategic Marketing</span>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Collaborations</span>
						</li>
					</ul>

					<a href={null}
						 class="group text-lg font-medium text-default-950">Read More
						<MoveRightIcon
							class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
						/>
					</a>
				</div>

				<div class="p-6">
					<div class="mx-auto">
						<RocketIcon class="inline-block h-12 w-12 text-default-950" />
					</div>
					<h2 class="mt-5 text-2xl font-medium text-default-950">
						Online Advertising
					</h2>
					<p class="mt-5 text-base">
						This pertains to how the product reaches the customer, including
						intermediaries such as wholesalers and retailers who facilitate
						convenient access to products or services.
					</p>

					<ul
						role="list"
						class="text-default-white -ms-3 mb-3 mt-4 text-sm">
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Experiential Marketing</span>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Event Marketing</span>
						</li>
						<li class="flex items-center gap-2 py-1">
							<DotIcon class="inline-block h-8 w-8 stroke-primary" />
							<span class="text-base text-default-950">Seasonal Campaigns</span>
						</li>
					</ul>

					<a href={null}
						 class="group text-lg font-medium text-default-950">Read More
						<MoveRightIcon
							class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100" />
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/marketing-2/components/Service.vue
<template>
  <section id="services" class="py-10 lg:py-20">
    <div class="container">
      <div class="mx-auto mb-14 max-w-xl text-center">
        <span
          class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
          >Our Services</span
        >
        <h2 class="mt-4 text-4xl/tight font-medium text-default-950">Marketing Solutions</h2>
        <p class="mt-5 text-base">
          The marketing mix symbolizes the fundamental instruments that marketers can employ to
          introduce their products or services to the market.
        </p>
      </div>

      <div class="border border-default-200">
        <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3">
          <div class="border-b border-default-200 p-6 md:border-e xl:border-0">
            <div class="mx-auto">
              <FileTextIcon class="inline-block h-12 w-12 text-default-950" />
            </div>
            <h2 class="mt-5 text-2xl font-medium text-default-950">Media Relations</h2>
            <p class="mt-5 text-base">
              Price need not be exclusively monetary; it can also encompass what is traded for the
              product or services, including energy or any sacrifices consumers make to acquire
              them.
            </p>

            <ul role="list" class="text-default-white -ms-3 mb-3 mt-4 text-sm">
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Seasonal Campaigns</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Digital Marketing</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Sponsorships</span>
              </li>
            </ul>

            <a href="javascript:void(0);" class="group text-lg font-medium text-default-950"
              >Read More
              <MoveRightIcon
                class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
              />
            </a>
          </div>

          <div class="border-b border-default-200 p-6 xl:border-x xl:border-b-0">
            <div class="mx-auto">
              <BoxIcon class="inline-block h-12 w-12 text-default-950" />
            </div>
            <h2 class="mt-5 text-2xl font-medium text-default-950">Marketing Consultancy</h2>
            <p class="mt-5 text-base">
              The product facets of marketing involve the specifications of the relevant products,
              goods, or services, and their alignment with the needs and desires of the end-users.
            </p>

            <ul role="list" class="text-default-white -ms-3 mb-3 mt-4 text-sm">
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Search Engine Optimization</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Strategic Marketing</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Collaborations</span>
              </li>
            </ul>

            <a href="javascript:void(0);" class="group text-lg font-medium text-default-950"
              >Read More
              <MoveRightIcon
                class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
              />
            </a>
          </div>

          <div class="p-6">
            <div class="mx-auto">
              <RocketIcon class="inline-block h-12 w-12 text-default-950" />
            </div>
            <h2 class="mt-5 text-2xl font-medium text-default-950">Online Advertising</h2>
            <p class="mt-5 text-base">
              This pertains to how the product reaches the customer, including intermediaries such
              as wholesalers and retailers who facilitate convenient access to products or services.
            </p>

            <ul role="list" class="text-default-white -ms-3 mb-3 mt-4 text-sm">
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Experiential Marketing</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Event Marketing</span>
              </li>
              <li class="flex items-center gap-2 py-1">
                <DotIcon class="inline-block h-8 w-8 stroke-primary" />
                <span class="text-base text-default-950">Seasonal Campaigns</span>
              </li>
            </ul>

            <a href="javascript:void(0);" class="group text-lg font-medium text-default-950"
              >Read More
              <MoveRightIcon
                class="inline-block h-6 w-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
              />
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { DotIcon, MoveRightIcon, FileTextIcon, BoxIcon, RocketIcon } from 'lucide-vue-next'
</script>
