// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/creative/blog.component.ts
import { Component } from '@angular/core'
import { LucideAngularModule } from 'lucide-angular'

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <!-- Start Blog -->
    <section id="blog" class="py-10 lg:py-20">
      <div class="container">
        <div class="mb-10 flex items-end justify-between">
          <div class="mx-auto max-w-2xl text-center">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Our Blog</span
            >
            <h2 class="my-4 text-3xl font-medium capitalize text-default-950">
              Read the latest news.
            </h2>
          </div>
        </div>
        <!-- flex End -->

        <div class="grid gap-6 xl:grid-cols-2">
          <div class="rounded-md border border-default-200 p-6">
            <div class="grid items-center gap-6 sm:grid-cols-5">
              <div class="col-span-2">
                <img
                  src="assets/images/landing/creative/img-6.png"
                  class="my-auto h-full w-full rounded-md"
                  alt=""
                />
              </div>

              <div class="group sm:col-span-3">
                <h3 class="mb-4 mt-3 text-3xl font-medium text-default-950">
                  Free advertising you online business.
                </h3>
                <p class="mb-5 mt-3 text-base">
                  Content king that means bringing and strategic approach.
                </p>
                <a
                  href="javascript:void(0);"
                  class="text-lg font-medium text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-4 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
              <!-- col-span-2 End -->
            </div>
            <!-- grid End -->
          </div>
          <!-- col End -->

          <div class="rounded-md border border-default-200 p-6">
            <div class="grid items-center gap-6 sm:grid-cols-5">
              <div class="group sm:col-span-3">
                <h3 class="mb-4 mt-3 text-3xl font-medium text-default-950">
                  Investment monitor top 2023
                </h3>
                <p class="mb-5 mt-3 text-base">
                  Content king that means bringing and strategic approach.
                </p>
                <a
                  href="javascript:void(0);"
                  class="group text-lg font-medium text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-4 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
              <!-- col-span-2 End -->

              <div class="col-span-2">
                <img
                  src="assets/images/landing/creative/img-8.png"
                  class="my-auto h-full w-full rounded-md"
                  alt=""
                />
              </div>
            </div>
            <!-- grid End -->
          </div>
          <!-- col End -->
        </div>
        <!-- Grid End -->
      </div>
      <!-- container End -->
    </section>
  `,
  styles: ``,
})
export class BlogComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/creative/components/Blog.vue
<template>
  <section id="blog" class="py-10 lg:py-20">
    <div class="container">
      <div class="flex items-end justify-between mb-10">
        <div class="max-w-2xl mx-auto text-center">
          <span
            class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
            >Our Blog</span
          >
          <h2 class="text-3xl font-medium capitalize text-default-950 my-4">
            Read the latest news.
          </h2>
        </div>
      </div>

      <div class="grid xl:grid-cols-2 gap-6">
        <BlogCard3 :blog="blogData[0]" />
        <BlogCard4 :blog="blogData[1]" />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import creativeImg6 from '@/assets/images/landing/creative/img-6.png'
import creativeImg8 from '@/assets/images/landing/creative/img-8.png'

import type { BlogType } from '@/types/landing'

import BlogCard3 from '@/components/widgets/BlogCard3.vue'
import BlogCard4 from '@/components/widgets/BlogCard4.vue'

const blogData: BlogType[] = [
  {
    image: creativeImg6,
    title: 'Free advertising you online business',
    description: 'Content king that means bringing and strategic approach.'
  },
  {
    image: creativeImg8,
    title: 'Investment monitor top 2023',
    description: 'Content king that means bringing and strategic approach.'
  }
]
</script>
