// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/agency2/since.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-since',
  standalone: true,
  imports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],

  template: `
    <!-- since Start -->
    <section class="relative py-10 lg:py-20 xl:py-0">
      <div class="container">
        <div
          class="relative grid grid-cols-1 items-center gap-12 xl:grid-cols-2"
        >
          <div class="mx-auto">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Since From</span
            >
            <h1
              class="my-4 max-w-lg text-4xl font-medium text-default-950 md:text-5xl/tight"
            >
              Keep pushing forward. We've got your back.
            </h1>
            <p class="max-w-md md:text-lg">
              Thing go wrong have questions. We've understand. So we have people
            </p>

            <div class="mt-10 flex flex-wrap items-center gap-16">
              <div class="flex items-center gap-6">
                <h2 class="text-5xl font-medium text-default-950">10k</h2>
                <p class="text-base">Happy Users <br />Around World</p>
              </div>

              <div class="flex items-center gap-6">
                <h2 class="text-5xl font-medium text-default-950">120k</h2>
                <p class="text-base">Projects <br />Already Done</p>
              </div>
            </div>
            <!-- flex end -->
          </div>
          <!-- col end -->

          <div class="relative mx-auto h-[600px] overflow-hidden">
            <div class="marquee">
              <div class="relative m-auto flex flex-col gap-6 overflow-hidden">
                <div
                  class="marquee-hero flex min-h-full flex-shrink-0 flex-col items-center justify-around gap-6"
                >
                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-1.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-2.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-3.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-4.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-5.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->
                </div>
                <!-- marquee-hero end -->

                <div
                  aria-hidden="true"
                  class="marquee-hero flex min-h-full flex-shrink-0 flex-col items-center justify-around gap-6"
                >
                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-1.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-2.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-3.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-4.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->

                  <div>
                    <div
                      class="max-w-xl rounded-md border border-default-200 bg-default-50 p-6"
                    >
                      <div class="flex items-center gap-5">
                        <img
                          src="assets/images/avatars/img-5.jpg"
                          class="size-16 rounded-full border-4 border-default-200"
                        />
                        <h3 class="text-lg font-medium text-default-950">
                          Leonard Heiser
                        </h3>
                      </div>
                      <!-- flex end -->
                      <p class="my-5 text-xl text-default-600">
                        I have been hiring people in this space for and numbers
                        of years and I have to be never seen this level of
                        professionalism.
                      </p>
                      <div class="flex items-center gap-1">
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                        <lucide-angular
                          name="star"
                          class="size-5 fill-yellow-400 stroke-yellow-400"
                        ></lucide-angular>
                      </div>
                      <!-- flex end -->
                    </div>
                  </div>
                  <!-- col end -->
                </div>
                <!-- marquee-hero end -->
              </div>
              <!-- flex end -->
            </div>
            <!-- marquee end -->
          </div>
          <!-- col end -->
        </div>
        <!-- grid end -->
      </div>
      <!-- container end -->
    </section>
    <!-- since end  -->
  `,
  styles: ``,
})
export class SinceComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Agency2/components/Since.tsx
import { allReviews } from "../data"
import ReviewCard from "./ReviewCard"

const Since = () => {
  return (
    <section className="relative xl:py-0 lg:py-20 py-10">
      <div className="container">
        <div className="grid xl:grid-cols-2 grid-cols-1 gap-12 items-center relative">
          <div className="mx-auto">
            <span className="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary">Since From</span>
            <h1 className="md:text-5xl/tight text-4xl font-medium text-default-950 max-w-lg my-4">Keep pushing forward. We've got your back.</h1>
            <p className="max-w-md md:text-lg">Thing go wrong have questions. We've understand. So we have people</p>
            <div className="flex flex-wrap items-center gap-16 mt-10">
              <div className="flex items-center gap-6">
                <h2 className="text-5xl font-medium text-default-950">10k</h2>
                <p className="text-base">Happy Users <br />Around World</p>
              </div>
              <div className="flex items-center gap-6">
                <h2 className="text-5xl font-medium text-default-950">120k</h2>
                <p className="text-base">Projects <br />Already Done</p>
              </div>
            </div>
          </div>
          <div className="mx-auto h-[600px] overflow-hidden relative">
            <div className="marquee">
              <div className="relative gap-6 m-auto flex flex-col overflow-hidden">
                <div className="marquee-hero gap-6 flex flex-col items-center justify-around flex-shrink-0 min-h-full">
                  {allReviews.map((review, idx) => (
                    <ReviewCard key={idx} review={review} />
                  ))}
                </div>
                <div aria-hidden="true" className="marquee-hero gap-6 flex flex-col items-center justify-around flex-shrink-0 min-h-full">
                  {allReviews.map((review, idx) => (
                    <ReviewCard key={idx} review={review} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Since
