// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Marketing/components/Features.jsx
import { LuBoxes, LuLayers, LuMonitor, LuMoveRight } from "react-icons/lu";
import { Link } from "react-router-dom";

import marketing4 from "@/assets/images/landing/marketing/img-4.jpg";

const Features = () => {
  return (
    <section id="features" className="py-10 lg:py-20">
      <div className="container">
        <div className="flex items-end justify-between mb-10">
          <div className="max-w-2xl mx-auto text-center">
            <span className="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary">
              Features
            </span>
            <h2 className="text-3xl font-medium capitalize text-default-950 my-4">
              We want to bring business &amp; the digital world together.
            </h2>
          </div>
        </div>
        <div className="grid lg:grid-cols-2 gap-6 items-center">
          <div>
            <div className="grid  grid-cols-1 items-center rounded-md overflow-hidden border border-default-200">
              <div className="group">
                <div className="flex flex-wrap items-center gap-6 p-6">
                  <div>
                    <LuLayers className="h-14 w-14 text-default-950" />
                  </div>
                  <div>
                    <h2 className="text-2xl text-default-950 font-medium mb-4">
                      Product Design
                    </h2>
                    <p className="text-base mb-6">
                      Lorem ipsum dummy text are used in this design
                    </p>
                    <Link to="" className="text-default-950 text-lg">
                      Read More
                      <LuMoveRight className="group-hover:opacity-100 opacity-0 w-6 h-6 inline-block transition-all duration-500 group-hover:translate-x-2 will-change-transform" />
                    </Link>
                  </div>
                </div>
              </div>
              <div className="group border-y border-default-200">
                <div className="flex flex-wrap items-center gap-6 p-6">
                  <div>
                    <LuMonitor className="h-14 w-14 text-default-950" />
                  </div>
                  <div>
                    <h2 className="text-2xl text-default-950 font-medium mb-4">
                      Marketing Strategy
                    </h2>
                    <p className="text-base mb-6">
                      Nullam dictum felis eu pede mollis pretium.
                    </p>
                    <Link to="" className="text-default-950 text-lg">
                      Read More
                      <LuMoveRight className="group-hover:opacity-100 opacity-0 w-6 h-6 inline-block transition-all duration-500 group-hover:translate-x-2 will-change-transform" />
                    </Link>
                  </div>
                </div>
              </div>
              <div className="group">
                <div className="flex flex-wrap items-center gap-6 p-6">
                  <div>
                    <LuBoxes className="h-14 w-14 text-default-950" />
                  </div>
                  <div>
                    <h2 className="text-2xl text-default-950 font-medium mb-4">
                      E-Commerce
                    </h2>
                    <p className="text-base mb-6">
                      Maecenas malesuada. Praesent congue erat at massa.
                    </p>
                    <Link to="" className="text-default-950 text-lg">
                      Read More
                      <LuMoveRight className="group-hover:opacity-100 opacity-0 w-6 h-6 inline-block transition-all duration-500 group-hover:translate-x-2 will-change-transform" />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <img src={marketing4} className="mx-auto" />
          </div>
        </div>
      </div>
    </section>
  );
};

export default Features;

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/creative/features.component.ts
import { Component } from '@angular/core'
import { LucideAngularModule } from 'lucide-angular'

@Component({
  selector: 'app-features',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <!-- Start features -->
    <section id="features" class="py-10 lg:py-20">
      <div class="container">
        <div class="mb-10 flex items-end justify-between">
          <div class="mx-auto max-w-2xl text-center">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >FEATUREO FEATURES</span
            >
            <h2 class="my-4 text-4xl font-medium capitalize text-default-950">
              Our Features
            </h2>
          </div>
        </div>
        <!-- flex End-->
        <div
          class="grid grid-cols-1 items-center overflow-hidden rounded-md border border-default-200 md:grid-cols-2 xl:grid-cols-3"
        >
          @for (item of creativeservice; track $index) {
            <div class="{{ item.class }}">
              <div class="p-8 sm:p-10">
                <span>
                  <lucide-angular
                    name="{{ item.icon }}"
                    class="size-14 text-default-950"
                  ></lucide-angular>
                </span>
                <h2 class="mb-4 mt-8 text-2xl font-medium text-default-950">
                  {{ item.title }}
                </h2>
                <p class="mb-6 text-base text-default-600">
                  {{ item.content }}
                </p>
                <a
                  href="javascript:void(0);"
                  class="text-lg font-medium text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
            </div>
          }
          <!-- end col -->
        </div>
        <!-- grid End-->
      </div>
      <!-- container End-->
    </section>
    <!-- End features -->
  `,
  styles: ``,
})
export class FeaturesComponent {
  creativeservice = [
    {
      class: 'group h-full border-b border-default-200',
      icon: 'component',
      title: 'Developer',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
    {
      class: 'group h-full border-b border-default-200 md:border-s',
      icon: 'monitor',
      title: 'Web Design',
      content:
        'In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.',
    },
    {
      class: 'group h-full border-b border-default-200 xl:border-s',
      icon: 'layers',
      title: 'Digital Product Design',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
    {
      class: 'group h-full border-b border-s border-default-200 xl:border-0',
      icon: 'layout-grid',
      title: 'Branding & Design',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
    {
      class:
        'group h-full border-b border-default-200 md:border-b-0 xl:border-s',
      icon: 'figma',
      title: 'Ui/Ux & Design',
      content:
        'Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu.',
    },
    {
      class: 'group h-full border-default-200 md:border-s',
      icon: 'paintbrush',
      title: 'Branding & Design',
      content:
        'Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus.',
    },
  ]
}
