// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/landing/Hosting/components/Features.tsx
import hosting3 from '@/assets/images/landing/hosting/3.svg'
import hosting5 from '@/assets/images/landing/hosting/5.svg'
import { LuMoveRight } from 'react-icons/lu'
import { Link } from 'react-router-dom'

const Features = () => {
  return (
    <>
      <section id="features" className="py-10 lg:py-20">
        <div className="container">
          <div className="grid md:grid-cols-2 gap-6 items-center">
            <div>
              <img src={hosting5} />
            </div>
            <div>
              <span className="text-sm uppercase text-default-950">Trusted security</span>
              <h2 className="md:text-4xl text-3xl font-medium text-default-950 my-5">Reliable security right from the start.</h2>
              <p className="text-base text-default-950 mb-5">Lorem ipsum originated from the scrambled, Latin text of Cicero's 1st-century BC work, De Finibus, and has since become ubiquitous lorem ipsum.</p>
              <Link to="" className="inline-flex gap-2 text-xl items-center relative text-primary group">
                <span className="absolute h-px w-7/12 group-hover:w-full transition-all duration-500 rounded bg-primary/80 -bottom-0" />
                Discover more by clicking here
                <LuMoveRight  className="h-5 w-5" />
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="py-10 lg:py-20">
        <div className="container">
          <div className="grid md:grid-cols-2 gap-6 items-center">
            <div>
              <span className="text-sm uppercase text-default-950">Site transfer</span>
              <h2 className="md:text-4xl text-3xl font-medium text-default-950 my-5">Seamless migration with lightning speed and zero downtime.</h2>
              <p className="text-base text-default-950 mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
              <Link to="" className="inline-flex gap-2 text-xl items-center relative text-primary group">
                <span className="absolute h-px w-7/12 group-hover:w-full transition-all duration-500 rounded bg-primary/80 -bottom-0" />
                Discover more by clicking here
                <LuMoveRight className="h-5 w-5" />
              </Link>
            </div>
            <div>
              <img src={hosting3} className="h-96" />
            </div>
          </div>
        </div>
      </section>
    </>

  )
}

export default Features

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/finance/features.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-features',
  standalone: true,
  imports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
  template: ` <div class="grid items-center gap-6 lg:grid-cols-2">
    <div>
      <span
        class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
        >Highlighted Projects</span
      >
      <h2 class="mt-4 text-4xl/tight font-medium text-default-950">
        Streamline Data Integrations: Simplify finance with Vault
      </h2>
      <p class="mt-5 text-base text-default-900">
        Save time on financial tasks by automating them with Vault. Consectetur
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua.
      </p>
      <div class="group mt-5">
        <a
          href="javascript:void(0);"
          class="inline-flex items-center justify-center gap-2 rounded-full bg-primary/20 px-4 py-2 text-sm text-primary transition-all duration-200 hover:bg-primary hover:text-white"
          >Read More
          <lucide-angular
            name="move-right"
            class="inline-block size-6"
          ></lucide-angular>
        </a>
      </div>
    </div>

    <div>
      <img
        src="assets/images/landing/finance/img-8.png"
        class="h-full w-full rounded-lg"
        alt=""
      />
    </div>
  </div>`,
  styles: ``,
})
export class FeatureComponent {}
