// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/agency/blog.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
  template: `
    <!-- Start Blog -->
    <section id="blog" class="py-10 lg:py-20">
      <div class="container">
        <div class="mb-10 flex items-end justify-between">
          <div class="mx-auto max-w-2xl text-center">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Our Blog</span
            >
            <h2 class="my-4 text-3xl font-medium capitalize text-default-950">
              Latest from our blog
            </h2>
            <p class="text-base">
              In this guide, we're going to share the essential SEO ranking
              factors you need to dominate search. By the end of this post,
              you'll have a well-optimized site
            </p>
          </div>
        </div>
        <!-- flex End-->

        <div class="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
          <div class="overflow-hidden rounded-lg border border-default-200">
            <div class="group p-6">
              <div class="relative overflow-hidden rounded-md">
                <img
                  src="assets/images/landing/agency/img-13.jpg"
                  class="rounded-md"
                  alt=""
                />
                <div class="absolute inset-0 bg-black/40"></div>
              </div>

              <div class="mt-6 flex gap-5">
                <div>
                  <h2 class="text-3xl font-medium text-default-950">06</h2>
                  <p class="text-lg uppercase text-default-800">Sep</p>
                </div>
                <div>
                  <h2 class="text-2xl font-medium text-default-950">
                    Brilliant minds.
                  </h2>
                  <p class="mb-5 mt-3 text-base">
                    Lorem ipsum dolor sit amet, proin gravida nibh vel velit
                    auctor aliquet. Aenean sollictudin, lorem quis bibendum
                    auctor...
                  </p>
                  <a href="javascript:void(0);" class="text-lg text-default-950"
                    >Read More
                    <lucide-angular
                      name="move-right"
                      class="inline-block size-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                    ></lucide-angular>
                  </a>
                </div>
              </div>
              <!-- flex End -->
            </div>
          </div>
          <!-- col End -->

          <div class="overflow-hidden rounded-lg border border-default-200">
            <div class="group p-6">
              <div class="relative overflow-hidden rounded-md">
                <img
                  src="assets/images/landing/agency/img-14.jpg"
                  class="rounded-md"
                  alt=""
                />
                <div class="absolute inset-0 bg-black/40"></div>
              </div>

              <div class="mt-6 flex gap-5">
                <div>
                  <h2 class="text-3xl font-medium text-default-950">05</h2>
                  <p class="text-lg uppercase text-default-800">Sep</p>
                </div>
                <div>
                  <h2 class="text-2xl font-medium text-default-950">
                    Digital Marketing.
                  </h2>
                  <p class="mb-5 mt-3 text-base">
                    Lorem ipsum dolor sit amet, proin gravida nibh vel velit
                    auctor aliquet. Aenean sollictudin, lorem quis bibendum
                    auctor...
                  </p>
                  <a href="javascript:void(0);" class="text-lg text-default-950"
                    >Read More
                    <lucide-angular
                      name="move-right"
                      class="inline-block size-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                    ></lucide-angular>
                  </a>
                </div>
              </div>
              <!-- flex End -->
            </div>
          </div>
          <!-- col End -->

          <div class="overflow-hidden rounded-lg border border-default-200">
            <div class="group p-6">
              <div class="relative overflow-hidden rounded-md">
                <img
                  src="assets/images/landing/agency/img-15.jpg"
                  class="rounded-md"
                  alt=""
                />
                <div class="absolute inset-0 bg-black/40"></div>
              </div>

              <div class="mt-6 flex gap-5">
                <div>
                  <h2 class="text-3xl font-medium text-default-950">04</h2>
                  <p class="text-lg uppercase text-default-800">Sep</p>
                </div>
                <div>
                  <h2 class="text-2xl font-medium text-default-950">
                    Good thinking.
                  </h2>
                  <p class="mb-5 mt-3 text-base">
                    Lorem ipsum dolor sit amet, proin gravida nibh vel velit
                    auctor aliquet. Aenean sollictudin, lorem quis bibendum
                    auctor...
                  </p>
                  <a href="javascript:void(0);" class="text-lg text-default-950"
                    >Read More
                    <lucide-angular
                      name="move-right"
                      class="inline-block size-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                    ></lucide-angular>
                  </a>
                </div>
              </div>
              <!-- flex End -->
            </div>
          </div>
          <!-- col End -->
        </div>
        <!-- Grid End -->
      </div>
      <!-- container End-->
    </section>
    <!-- End Blog -->
  `,
  styles: ``,
})
export class BlogComponent {}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Vue/Vue/src/views/landings/agency-1/Blog.vue
<template>
  <section id="blog" class="lg:py-20 py-10">
    <div class="container">
      <div class="flex items-end justify-between mb-10">
        <div class="max-w-2xl mx-auto text-center">
          <span class="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary"
            >Our Blog</span
          >
          <h2 class="text-3xl font-medium capitalize text-default-950 my-4">Latest from our blog</h2>
          <p class="text-base font-medium text-default-800">
            In this guide, we're going to share the essential SEO ranking factors you need to dominate search. By the end of this post, you'll have a
            well-optimized site
          </p>
        </div>
      </div>

      <div class="grid xl:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-6">
        <BlogCard1 v-for="(blog, idx) in blogData" :key="blog.title" :blog="blog" />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import BlogCard1 from '@/components/widgets/BlogCard1.vue'

import type { BlogType } from '@/types/landing'

import agencyImg13 from '@/assets/images/landing/agency/img-13.jpg'
import agencyImg14 from '@/assets/images/landing/agency/img-14.jpg'
import agencyImg15 from '@/assets/images/landing/agency/img-15.jpg'

const blogData: BlogType[] = [
  {
    image: agencyImg13,
    publish: {
      date: 6,
      month: 'Sep',
    },
    title: 'Brilliant minds.',
    description: 'Lorem ipsum dolor sit amet, proin gravida nibh vel velit auctor aliquet. Aenean sollictudin, lorem quis bibendum auctor...',
  },
  {
    image: agencyImg14,
    publish: {
      date: 5,
      month: 'Sep',
    },
    title: 'Digital Marketing.',
    description: 'Lorem ipsum dolor sit amet, proin gravida nibh vel velit auctor aliquet. Aenean sollictudin, lorem quis bibendum auctor...',
  },
  {
    image: agencyImg15,
    publish: {
      date: 4,
      month: 'Sep',
    },
    title: 'Good thinking.',
    description: 'Lorem ipsum dolor sit amet, proin gravida nibh vel velit auctor aliquet. Aenean sollictudin, lorem quis bibendum auctor...',
  },
]
</script>
