// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Vue/Vue/src/views/landings/marketing-2/index.vue
<template>
  <Navbar1 menu-position="fixed" :navbar-link="navLinkData" btn-text="Download" :btn-icon="DownloadCloudIcon" />

  <Marketing2Hero />

  <section class="lg:-mt-[72px]">
    <MarqueeGroup custom-class="bg-default-100 dark:bg-default-50 border-none" />
  </section>

  <About />

  <Service />

  <Portfolio />

  <Step />

  <Testimonial />

  <Action />

  <Blog />

  <Cta />

  <Contact />

  <Footer />

  <BackToTop />
</template>

<script setup lang="ts">
import Navbar1 from '@/layout/partials/Navbar1.vue'
import Marketing2Hero from '@/components/heros/Marketing2Hero.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import About from '@/views/landings/marketing-2/About.vue'
import Service from '@/views/landings/marketing-2/Service.vue'
import Portfolio from '@/views/landings/marketing-2/Portfolio.vue'
import Step from '@/views/landings/marketing-2/Step.vue'
import Testimonial from '@/views/landings/marketing-2/Testimonial.vue'
import Action from '@/views/landings/marketing-2/Action.vue'
import Blog from '@/views/landings/marketing-2/Blog.vue'
import Cta from '@/views/landings/marketing-2/Cta.vue'
import Contact from '@/views/landings/marketing-2/Contact.vue'
import Footer from '@/layout/partials/Footer.vue'
import BackToTop from '@/layout/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home',
  },
  {
    id: 'about',
    name: 'About',
  },
  {
    id: 'services',
    name: 'Services',
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
  },
  {
    id: 'blog',
    name: 'Blog',
  },
  {
    id: 'contact',
    name: 'Contact',
  },
]
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/marketing-2/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import About from './About.svelte';
	import Service from './Service.svelte';
	import Portfolio from './Portfolio.svelte';
	import Step from './Step.svelte';
	import Testimonial from './Testimonial.svelte';
	import Action from './Action.svelte';
	import Blog from './Blog.svelte';
	import Cta from './Cta.svelte';
	import Contact from './Contact.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'about',
			name: 'About'
		},
		{
			id: 'services',
			name: 'Services'
		},
		{
			id: 'portfolio',
			name: 'Portfolio'
		},
		{
			id: 'testimonial',
			name: 'Testimonial'
		},
		{
			id: 'blog',
			name: 'Blog'
		},
		{
			id: 'contact',
			name: 'Contact'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<section class="lg:-mt-[72px]">
	<MarqueeGroup customClass="bg-default-100 dark:bg-default-50 border-none" />
</section>

<About />

<Service />

<Portfolio />

<Step />

<Testimonial />

<Action />

<Blog />

<Cta />

<Contact />
