// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/hosting/Extra.svelte
<script lang="ts">
	import { MoveRightIcon } from 'lucide-svelte';
</script>

<section class="py-10 lg:py-20">
	<div class="container">
		<div class="mx-auto mb-12 max-w-xl text-center">
			<h2 class="text-3xl font-medium text-default-950 md:text-4xl">
				Didn't find the answer you were looking for?
			</h2>

			<div class="relative mx-auto mt-6 w-full lg:w-96">
				<div class="group">
					<div class="w-full transition-all duration-500 group-hover:-translate-y-2 group-hover:translate-x-2">
						<div
							class="relative z-10 flex h-[68px] items-center justify-center bg-primary p-6">
							<a class="bg-primary text-xl text-white" href={null}>
								Feel free to submit your question
							</a>
						</div>
					</div>
					<div class="absolute left-0 top-0 -z-10 h-full w-full bg-default-950"></div>
				</div>
			</div>
		</div>

		<div class="bg-default-100 dark:bg-default-50">
			<div
				class="bg-[url('../images/other/bg-lines-2.png')] bg-cover bg-no-repeat p-10 text-center dark:bg-[url('../images/other/bg-lines-2-dark.png')] md:p-20">
				<h2 class="text-3xl font-medium text-default-950 md:text-4xl">
					Sign up today for top-notch web hosting services.
				</h2>

				<div class="mt-7 flex flex-wrap items-center justify-center gap-6">
					<a
						href={null}
						class="group relative inline-flex items-center gap-2 text-default-950 hover:text-primary md:text-xl">
                <span
									class="absolute -bottom-0 h-px w-7/12 rounded bg-default-50 transition-all duration-500 group-hover:w-full group-hover:bg-primary"
								></span>
						Discover more by clicking here
						<MoveRightIcon class="h-5 w-5" />
					</a>

					<div class="relative">
						<div class="group">
							<div
								class="relative z-10 transition-all duration-500 group-hover:-translate-y-2 group-hover:translate-x-2">
								<div class="bg-primary px-6 py-2">
									<a class="bg-primary text-xl text-white" href={null}>
										Get Started
									</a>
								</div>
							</div>
							<div class="absolute left-0 top-0 z-0 h-full w-full bg-default-950"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/pages/landings/hosting/components/Extra.vue
<template>
  <section class="py-10 lg:py-20">
    <div class="container">
      <div class="mx-auto mb-12 max-w-xl text-center">
        <h2 class="text-3xl font-medium text-default-950 md:text-4xl">
          Didn't find the answer you were looking for?
        </h2>

        <div class="relative mx-auto mt-6 w-full lg:w-96">
          <div class="group">
            <div
              class="w-full transition-all duration-500 group-hover:-translate-y-2 group-hover:translate-x-2"
            >
              <div class="relative z-10 flex h-[68px] items-center justify-center bg-primary p-6">
                <a class="bg-primary text-xl text-white" href="#">
                  Feel free to submit your question
                </a>
              </div>
            </div>
            <div class="absolute left-0 top-0 -z-10 h-full w-full bg-default-950"></div>
          </div>
        </div>
      </div>

      <div class="bg-default-100 dark:bg-default-50">
        <div
          class="bg-[url('../images/other/bg-lines-2.png')] bg-cover bg-no-repeat p-10 text-center dark:bg-[url('../images/other/bg-lines-2-dark.png')] md:p-20"
        >
          <h2 class="text-3xl font-medium text-default-950 md:text-4xl">
            Sign up today for top-notch web hosting services.
          </h2>

          <div class="mt-7 flex flex-wrap items-center justify-center gap-6">
            <a
              href="#"
              class="group relative inline-flex items-center gap-2 text-default-950 hover:text-primary md:text-xl"
            >
              <span
                class="absolute -bottom-0 h-px w-7/12 rounded bg-default-50 transition-all duration-500 group-hover:w-full group-hover:bg-primary"
              ></span>
              Discover more by clicking here
              <MoveRightIcon class="h-5 w-5" />
            </a>

            <div class="relative">
              <div class="group">
                <div
                  class="relative z-10 transition-all duration-500 group-hover:-translate-y-2 group-hover:translate-x-2"
                >
                  <div class="bg-primary px-6 py-2">
                    <a class="bg-primary text-xl text-white" href="#"> Get Started </a>
                  </div>
                </div>
                <div class="absolute left-0 top-0 z-0 h-full w-full bg-default-950"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { MoveRightIcon } from 'lucide-vue-next'
</script>
