// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/landings/finance/+page.svelte
<script lang="ts">
	import type { NavbarLinkType } from '$lib/types/layout';
	import Navbar1 from '$lib/components/layouts/Navbar1.svelte';
	import Hero from './Hero.svelte';
	import MarqueeGroup from '$lib/components/MarqueeGroup.svelte';
	import Testimonial from './Testimonial.svelte';
	import Feature from './Feature.svelte';
	import Asset from './Asset.svelte';
	import Onboarding from './Onboarding.svelte';
	import Cta from './Cta.svelte';

	const navLinkData: NavbarLinkType[] = [
		{
			id: 'home',
			name: 'Home'
		},
		{
			id: 'experts',
			name: 'Experts'
		},
		{
			id: 'features',
			name: 'Features'
		},
		{
			id: 'assets',
			name: 'Assets'
		},
		{
			id: 'onboarding',
			name: 'Onboarding'
		}
	];
</script>

<Navbar1 menuPosition="fixed" navbarLink={navLinkData} />

<Hero />

<section>
	<MarqueeGroup customClass="bg-default-100 dark:bg-default-50 py-4" />
</section>

<Testimonial />

<Feature />

<Asset />

<Onboarding />

<Cta />

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Vue/Vue/src/views/landings/finance/index.vue
<template>
  <Navbar1 menu-position="fixed" :navbar-link="navLinkData" btn-text="Download" :btn-icon="DownloadCloudIcon" />

  <FinanceHero />

  <section>
    <MarqueeGroup custom-class="bg-default-100 dark:bg-default-50 py-4" />
  </section>

  <Testimonial />

  <Feature />

  <Asset />

  <Onboarding />

  <Cta />

  <Footer />

  <BackToTop />
</template>

<script setup lang="ts">
import Navbar1 from '@/layout/partials/Navbar1.vue'
import FinanceHero from '@/components/heros/FinanceHero.vue'
import MarqueeGroup from '@/components/MarqueeGroup.vue'
import Testimonial from '@/views/landings/finance/Testimonial.vue'
import Feature from '@/views/landings/finance/Feature.vue'
import Asset from '@/views/landings/finance/Asset.vue'
import Onboarding from '@/views/landings/finance/Onboarding.vue'
import Cta from '@/views/landings/finance/Cta.vue'
import Footer from '@/layout/partials/Footer.vue'
import BackToTop from '@/layout/partials/BackToTop.vue'

import { DownloadCloudIcon } from 'lucide-vue-next'

import type { NavbarLinkType } from '@/types/layout'

const navLinkData: NavbarLinkType[] = [
  {
    id: 'home',
    name: 'Home',
  },
  {
    id: 'experts',
    name: 'Experts',
  },
  {
    id: 'features',
    name: 'Features',
  },
  {
    id: 'assets',
    name: 'Assets',
  },
  {
    id: 'onboarding',
    name: 'Onboarding',
  },
]
</script>
