// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/admin/Chat/index.tsx
import { useState } from "react"
import ChatArea from "./components/ChatArea"
import ChatUsers from "./components/ChatUsers"
import { type ChatUser, users } from "./data"
import { AdminBreadcrumb } from "@/components"

const Chat = () => {
  const [selectedUser, setSelectedUser] = useState<ChatUser>(users[1])

  /**
   * On user change
   */
  const onUserChange = (user: ChatUser) => {
    setSelectedUser(user)
  }
  return (
    <>
      <AdminBreadcrumb title="Chat" />
      <section>
        <div className="container">
          <div className="my-6 space-y-6">
            <div className="grid gap-4 lg:grid-cols-3">
              <div className="lg:col-span-1">
                <ChatUsers onUserSelect={onUserChange} selectedUser={selectedUser} />
              </div>
              {/* Chat Conversation */}
              <div className="lg:col-span-2">
                <ChatArea selectedUser={selectedUser} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>

  )
}

export default Chat

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/admin/chat/+page.svelte
<script lang="ts">
	import AdminPageTitle from '$lib/components/layouts/AdminPageTitle.svelte';
	import ContactList from './ContactList.svelte';
	import Chat from './Chat.svelte';
</script>

<AdminPageTitle title="Chat" subtitle="Admin" />

<section>
	<div class="container">
		<div class="my-6 space-y-6">
			<div class="grid gap-4 lg:grid-cols-3">
				<div class="lg:col-span-1">
					<ContactList />
				</div>

				<div class="lg:col-span-2">
					<Chat />
				</div>
			</div>
		</div>
	</div>
</section>
