// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/components/sections/Portfolio.vue
<template>
  <section id="portfolio" class="pt-20 pb-10">
    <div class="flex items-end justify-between mb-10">
      <div class="max-w-2xl mx-auto text-center">
        <span
          class="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary"
          >{{ tag }}</span
        >
        <h2 class="text-4xl font-medium capitalize text-default-950 my-4">{{ title }}</h2>
      </div>
    </div>

    <div>
      <Swiper
        class="rounded-md relative"
        :modules="[Thumbs, FreeMode]"
        :slidesPerView="1"
        :spaceBetween="30"
        :centeredSlides="true"
        :loop="true"
        :autoplay="{
          delay: 3500,
          disableOnInteraction: false
        }"
        :breakpoints="{
          400: {
            slidesPerView: 1,
            spaceBetween: 20
          },
          768: {
            slidesPerView: 2,
            spaceBetween: 40
          }
        }"
      >
        <SwiperSlide v-for="(project, idx) in projectList" :key="project.image">
          <div class="relative group rounded-3xl overflow-hidden">
            <img :src="project.image" class="h-full w-full" alt="" />
            <div class="absolute inset-0 bg-black/60"></div>
            <div
              class="absolute inset-x-0 top-1/2 opacity-0 group-hover:opacity-100 transition-all duration-700"
            >
              <div class="text-center">
                <h5 class="inline-block text-xl font-medium text-white bg-black py-1 px-3 mb-1">
                  {{ project.category }}
                </h5>
                <br />
                <h2 class="inline-block text-2xl font-medium text-white bg-black py-1 px-3">
                  {{ project.name }}
                </h2>
              </div>
            </div>
          </div>
        </SwiperSlide>
      </Swiper>
    </div>
  </section>
</template>

<script setup lang="ts">
import { FreeMode, Thumbs } from 'swiper/modules'
import { Swiper, SwiperSlide } from 'swiper/vue'

import type { ProjectType } from '@/types/landing'
import type { PropType } from 'vue'

defineProps({
  projectList: {
    type: Array as PropType<ProjectType[]>,
    required: true
  },
  tag: {
    type: String,
    required: true
  },
  title: {
    type: String,
    required: true
  }
})
</script>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/components/portfolio/portfolio.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input, input } from '@angular/core'
import { FreeMode, Thumbs } from 'swiper/modules'
import { SwiperOptions } from 'swiper/types'
import { SwiperDirective } from '../swiper-directive.component'
import { register } from 'swiper/element/bundle'
import { swiperImage } from '@app/landing/agency/portfolio.component'

register()
@Component({
  selector: 'app-portfolio',
  standalone: true,
  imports: [SwiperDirective],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './portfolio.component.html',
  styles: ``,
})
export class PortfolioComponent {
  @Input() Swiper!: swiperImage[]

  // hoportfolio swiper
  swiperConfig: SwiperOptions = {
    modules: [Thumbs, FreeMode],
    initialSlide: 2,
    slidesPerView: 3,
    spaceBetween: 30,
    centeredSlides: true,
    loop: true,
    autoplay: {
      delay: 3500,
      disableOnInteraction: false,
    },
    breakpoints: {
      400: {
        slidesPerView: 1,
        spaceBetween: 20,
      },
      768: {
        slidesPerView: 2,
        spaceBetween: 40,
      },
    },
  }
}

<!-- Start Portfolio -->
<section id="portfolio" class="pb-10 pt-20">
  <div class="mb-10 flex items-end justify-between">
    <div class="mx-auto max-w-2xl text-center">
      <span
        class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
        >Our Portfolio</span
      >
      <h2 class="my-4 text-4xl font-medium capitalize text-default-950">
        Selected Projects.
      </h2>
    </div>
  </div>
  <!-- flex End -->

  <div>
    <!--Start Swiper -->
    <div id="auth_swiper" class="swiper relative rounded-md">
      <swiper-container
        class="swiper-wrapper"
        init="false"
        [config]="swiperConfig"
      >
        @for (item of Swiper; track $index) {
          <swiper-slide class="swiper-slide">
            <div class="group relative overflow-hidden rounded-3xl">
              <img src="{{ item.image }}" class="h-full w-full" alt="" />
              <div class="absolute inset-0 bg-black/60"></div>
              <div
                class="absolute inset-x-0 top-1/2 opacity-0 transition-all duration-700 group-hover:opacity-100"
              >
                <div class="text-center">
                  <h5
                    class="mb-1 inline-block bg-black px-3 py-1 text-xl font-medium text-white"
                  >
                    {{ item.title }}
                  </h5>
                  <br />
                  <h2
                    class="inline-block bg-black px-3 py-1 text-2xl font-medium text-white"
                  >
                    {{ item.content }}
                  </h2>
                </div>
              </div>
            </div>
          </swiper-slide>
        }
        <!-- swiper-slide End -->
      </swiper-container>
    </div>
    <!--End Swiper -->
  </div>
</section>
<!-- End Portfolio -->
