// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/TS/src/pages/admin/Project/index.tsx
import { AdminBreadcrumb } from "@/components"
import { projects } from "./data"
import ProjectCard from "./components/ProjectCard"

const Project = () => {
  return (
    <>
      <AdminBreadcrumb title="Project" />
      <section>
        <div className="container">
          <div className="my-6 space-y-6">
            <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
              {projects.map((project, idx) => (
                <ProjectCard project={project} key={idx} />
              ))}
            </div>
          </div>
        </div>
      </section>
    </>

  )
}

export default Project

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/routes/admin/project/+page.svelte
<script lang="ts">
	import AdminPageTitle from '$lib/components/layouts/AdminPageTitle.svelte';
	import ProjectCard3 from '$lib/components/widgets/ProjectCard3.svelte';
	import { projectData } from './data';
</script>


<AdminPageTitle title="Project" subtitle="Admin" />

<section>
	<div class="container">
		<div class="my-6 space-y-6">
			<div class="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
				{#each projectData as project}
					<ProjectCard3 {project} />
				{/each}
			</div>
		</div>
	</div>
</section>
