// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/components/admin-footer/admin-footer.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-admin-footer',
  standalone: true,
  imports: [],
  template: `
    <footer
      class="w-full border-t border-default-200 bg-white py-4 dark:bg-default-50"
    >
      <div class="container">
        <div class="grid items-center gap-6 lg:grid-cols-2">
          <p class="text-center text-default-900 lg:text-start">
            {{ year }}
            © AeroPage. Crafted and Coded with
            <span class="text-red-500">❤️</span> by
            <a
              class="text-primary-700"
              href="https://coderthemes.com/"
              target="_blank"
              >Coderthemes</a
            >
          </p>

          <div
            class="hidden justify-center gap-6 text-center lg:flex lg:justify-end"
          >
            <a href="javascript:void(0)" class="font-medium text-default-500">
              Terms
            </a>
            <a href="javascript:void(0)" class="font-medium text-default-500">
              Privacy
            </a>
            <a href="javascript:void(0)" class="font-medium text-default-500">
              Cookies
            </a>
          </div>
        </div>
      </div>
    </footer>
  `,
  styles: ``,
})
export class AdminFooterComponent {
  year = new Date().getFullYear()
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/layouts/partials/AdminFooter.vue
<template>
  <footer class="w-full border-t border-default-200 bg-white py-4 dark:bg-default-50">
    <div class="container">
      <div class="grid items-center gap-6 lg:grid-cols-2">
        <p class="text-center text-default-900 lg:text-start">
          {{ year }}
          © AeroPage. Crafted and Coded with
          <span class="text-red-500">❤️</span> by
          <a class="text-primary-700" href="https://coderthemes.com/" target="_blank"
            >Coderthemes</a
          >
        </p>

        <div class="hidden justify-center gap-6 text-center lg:flex lg:justify-end">
          <a href="javascript:void(0)" class="font-medium text-default-500"> Terms </a>
          <a href="javascript:void(0)" class="font-medium text-default-500"> Privacy </a>
          <a href="javascript:void(0)" class="font-medium text-default-500"> Cookies </a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
const year = new Date().getFullYear()
</script>
