// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Sveltekit/Sveltekit/src/lib/components/layouts/BackToTop.svelte
<script lang="ts">
	import { MoonIcon, SunIcon, ChevronUpIcon } from 'lucide-svelte';
	import { preferences, currentTheme } from '$lib/stores/preference';
	import { onMount } from 'svelte';

	let isButtonVisible: boolean = false;

	const toggleTheme = () => {

		const newTheme: 'light' | 'dark' = (currentTheme === 'light') ? 'dark' : 'light';
		preferences.set({ theme: newTheme });

		const html = document.getElementsByTagName('html')[0];
		if (newTheme == 'light') {
			html.classList.remove('dark');
		} else {
			html.classList.add('dark');
		}
	};

	const backToTop = (e: Event) => {
		e.preventDefault();
		window.scrollTo({ top: 0, behavior: 'smooth' });
	};

	onMount(() => {
		window.addEventListener('scroll', () => {
			isButtonVisible = window.scrollY > 72;
		});
	});
</script>

<div class="fixed bottom-5 end-5 z-40 flex flex-col items-center gap-1">
	<!-- Back to Top -->
	<button
		class={`z-10 flex h-10 w-10 items-center justify-center rounded-full bg-primary/20 text-primary shadow-[inset_0px_0px_12px_0px] shadow-primary/40 backdrop-blur-3xl transition-all duration-500 ${!isButtonVisible ? 'translate-x-16':''}`}
		on:click={backToTop}
	>
		<ChevronUpIcon class="h-4 w-4" />
	</button>

	<!-- Light/Dark Toggle -->
	<button class="z-20 rounded-lg bg-primary text-white" on:click={toggleTheme}>
		{#if (currentTheme === 'light')}
    <span class="flex h-9 w-9 items-center justify-center" id="light-theme">
      <MoonIcon class="h-5 w-5" />
    </span>
		{/if}
		{#if (currentTheme === 'dark')}
		<span class="flex h-9 w-9 items-center justify-center" id="dark-theme">
       <SunIcon class="h-5 w-5" />
    </span>
		{/if}
	</button>
</div>

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/layouts/partials/BackToTop.vue
<template>
  <div class="fixed bottom-5 end-5 z-40 flex flex-col items-center gap-1">
    <!-- Back to Top -->
    <button
      class="z-10 flex h-10 w-10 items-center justify-center rounded-full bg-primary/20 text-primary shadow-[inset_0px_0px_12px_0px] shadow-primary/40 backdrop-blur-3xl transition-all duration-500"
      :class="{ 'translate-x-16': !isButtonVisible }"
      @click="backToTop"
    >
      <ChevronUpIcon class="h-4 w-4" />
    </button>

    <!-- Light/Dark Toggle -->
    <button class="z-20 rounded-lg bg-primary text-white" @click="toggleTheme">
      <span
        v-if="useTheme.theme === 'light'"
        class="flex h-9 w-9 items-center justify-center"
        id="light-theme"
      >
        <MoonIcon class="h-5 w-5" />
      </span>
      <span
        v-if="useTheme.theme === 'dark'"
        class="flex h-9 w-9 items-center justify-center"
        id="dark-theme"
      >
        <SunIcon class="h-5 w-5" />
      </span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { useThemeStore } from '@/stores/themes'
import { ChevronUpIcon, MoonIcon, SunIcon } from 'lucide-vue-next'
import { onMounted, ref } from 'vue'

const useTheme = useThemeStore()

const toggleTheme = () => {
  const theme = useTheme.theme == 'light' ? 'dark' : 'light'
  useTheme.setTheme(theme)
  const html = document.getElementsByTagName('html')[0]
  if (theme == 'light') {
    html.classList.remove('dark')
  } else {
    html.classList.add('dark')
  }
}

const backToTop = (e: any) => {
  e.preventDefault()
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

let isButtonVisible = ref(false)

onMounted(() => {
  window.addEventListener('scroll', () => {
    if (window.scrollY > 72) {
      isButtonVisible.value = true
    } else {
      isButtonVisible.value = false
    }
  })
})
</script>
