// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/components/footer/footer.component.ts
import { Component } from '@angular/core'
import {
  LUCIDE_ICONS,
  LucideAngularModule,
  LucideIconProvider,
  icons,
} from 'lucide-angular'

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [LucideAngularModule],
  template: ` <!-- Footer -->
    <footer>
      <div class="border-y border-default-200">
        <div class="container py-20">
          <div class="grid gap-10 md:grid-cols-3 lg:gap-16 xl:grid-cols-5">
            <div class="md:col-span-3 xl:col-span-2">
              <div>
                <a href="javascript:void(0);">
                  <img
                    src="assets/images/logo-dark.png"
                    alt="logo"
                    class="flex h-10 dark:hidden"
                  />
                  <img
                    src="assets/images/logo-light.png"
                    alt="logo"
                    class="hidden h-10 dark:flex"
                  />
                </a>
                <p class="mt-6 text-base text-default-800">
                  Integer auctor aliquet martor, sed lorem malesuada eros
                  blandit eget. Proin lacinia mortoc id odio vestibulum.
                </p>
                <form class="mt-6 space-y-2">
                  <div class="relative">
                    <input
                      type="email"
                      id="subcribe"
                      class="h-12 w-full rounded-lg border-default-200 bg-default-100 py-4 pe-16 ps-4 text-default-950 placeholder:text-default-600 focus:border-default-200 focus:ring-0"
                      placeholder="Type Your Email"
                      name="email"
                    />
                    <button
                      type="submit"
                      class="absolute end-[6px] top-[6px] inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary/20 px-6 text-primary transition-all hover:bg-primary hover:text-white"
                    >
                      <lucide-angular
                        name="move-right"
                        class="size-6"
                      ></lucide-angular>
                    </button>
                  </div>
                </form>
                <!-- form End -->
              </div>
            </div>
            <!-- col End -->

            <div class="">
              <h5
                class="mb-4 font-medium text-default-800 lg:text-lg xl:text-xl"
              >
                Company
              </h5>
              <ul class="flex flex-col gap-3">
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >About</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Services</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Portfolio</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Blog</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Contact</a
                  >
                </li>
              </ul>
            </div>
            <!-- col End -->

            <div class="">
              <ul class="flex flex-col gap-3">
                <h5
                  class="mb-4 font-medium text-default-800 lg:text-lg xl:text-xl"
                >
                  Social Media
                </h5>
                <div class="space-y-3">
                  <a
                    href="javascript:void(0);"
                    class="group flex items-center gap-5"
                  >
                    <div
                      class="inline-flex size-10 items-center justify-center rounded-lg border border-default-300 text-default-800 transition-all group-hover:border-primary group-hover:bg-primary group-hover:text-white"
                    >
                      <lucide-angular
                        name="facebook"
                        class="size-5"
                      ></lucide-angular>
                    </div>
                    <h5 class="text-base font-medium text-default-800">
                      Facebook
                    </h5>
                  </a>

                  <a
                    href="javascript:void(0);"
                    class="group flex items-center gap-5"
                  >
                    <div
                      class="inline-flex size-10 items-center justify-center rounded-lg border border-default-300 text-default-800 transition-all group-hover:border-primary group-hover:bg-primary group-hover:text-white"
                    >
                      <lucide-angular
                        name="instagram"
                        class="size-5"
                      ></lucide-angular>
                    </div>
                    <h5 class="text-base font-medium text-default-800">
                      Instagram
                    </h5>
                  </a>

                  <a
                    href="javascript:void(0);"
                    class="group flex items-center gap-5"
                  >
                    <div
                      class="inline-flex size-10 items-center justify-center rounded-lg border border-default-300 text-default-800 transition-all group-hover:border-primary group-hover:bg-primary group-hover:text-white"
                    >
                      <lucide-angular
                        name="twitter"
                        class="size-5"
                      ></lucide-angular>
                    </div>
                    <h5 class="text-base font-medium text-default-800">
                      Twitter
                    </h5>
                  </a>

                  <a
                    href="javascript:void(0);"
                    class="group flex items-center gap-5"
                  >
                    <div
                      class="inline-flex size-10 items-center justify-center rounded-lg border border-default-300 text-default-800 transition-all group-hover:border-primary group-hover:bg-primary group-hover:text-white"
                    >
                      <lucide-angular
                        name="linkedin"
                        class="size-5"
                      ></lucide-angular>
                    </div>
                    <h5 class="text-base font-medium text-default-800">
                      Linkedin
                    </h5>
                  </a>
                </div>
              </ul>
            </div>
            <!-- col End -->

            <div class="">
              <h5
                class="mb-4 font-medium text-default-800 lg:text-lg xl:text-xl"
              >
                Legal & Press
              </h5>
              <ul class="flex flex-col gap-3">
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Privacy Policy</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Terms & Conditions</a
                  >
                </li>
                <li>
                  <a
                    href="javascript:void(0);"
                    class="text-base text-default-700 transition-all hover:text-default-950"
                    >Presskit</a
                  >
                </li>
              </ul>
            </div>
            <!-- col End -->
          </div>
          <!-- grid End -->
        </div>
        <!-- Container End -->
      </div>

      <div class="py-4">
        <div
          class="container flex h-full flex-wrap items-center justify-center text-center md:justify-between md:text-start"
        >
          <p class="text-base text-default-900">
            {{ year }}
            © AeroPage. Crafted and Coded with
            <span class="text-red-500">❤️</span> by
            <a
              class="text-primary-700"
              href="https://coderthemes.com/"
              target="_blank"
              >Coderthemes</a
            >
          </p>
          <p class="text-base">
            <a href="javascript:void(0);">Terms Conditions & Policy</a>
          </p>
        </div>
        <!-- Flex End -->
      </div>
    </footer>`,
  styles: ``,
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
})
export class FooterComponent {
  year = new Date().getFullYear()
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Nuxtjs/Nuxtjs/layouts/partials/Footer.vue
<template>
  <footer>
    <div class="border-y border-default-200">
      <div class="container py-20">
        <div class="grid xl:grid-cols-5 md:grid-cols-3 gap-10 lg:gap-16">
          <div class="xl:col-span-2 md:col-span-3">
            <div>
              <a href="#">
                <img :src="logoDark" alt="logo" class="h-10 flex dark:hidden" />
                <img :src="logoLight" alt="logo" class="h-10 hidden dark:flex" />
              </a>
              <p class="text-base text-default-800 mt-6">
                Integer auctor aliquet martor, sed lorem malesuada eros blandit eget. Proin lacinia
                mortoc id odio vestibulum.
              </p>
              <form class="space-y-2 mt-6">
                <div class="relative">
                  <input
                    type="email"
                    id="subcribe"
                    class="py-4 ps-4 pe-16 w-full h-12 placeholder:text-default-600 text-default-950 rounded-lg bg-default-100 border-default-200 focus:ring-0 focus:border-default-200"
                    placeholder="Type Your Email"
                    name="email"
                  />
                  <button
                    type="submit"
                    class="inline-flex items-center justify-center gap-2 px-6 absolute top-[6px] end-[6px] h-9 bg-primary/20 text-primary rounded-md transition-all hover:bg-primary hover:text-white"
                  >
                    <MoveRightIcon class="h-6 w-6" />
                  </button>
                </div>
              </form>
            </div>
          </div>

          <div class="">
            <h5 class="xl:text-xl lg:text-lg font-medium text-default-800 mb-4">Company</h5>
            <ul class="flex flex-col gap-3">
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >About</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Services</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Portfolio</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Blog</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Contact</a
                >
              </li>
            </ul>
          </div>

          <div class="">
            <ul class="flex flex-col gap-3">
              <h5 class="xl:text-xl lg:text-lg font-medium text-default-800 mb-4">Social Media</h5>
              <div class="space-y-3">
                <a href="javascript:void(0);" class="flex items-center gap-5 group">
                  <div
                    class="h-10 w-10 inline-flex items-center justify-center border border-default-300 text-default-800 rounded-lg transition-all group-hover:bg-primary group-hover:text-white group-hover:border-primary"
                  >
                    <FacebookIcon class="h-5 w-5" />
                  </div>
                  <h5 class="text-base font-medium text-default-800">Facebook</h5>
                </a>

                <a href="javascript:void(0);" class="flex items-center gap-5 group">
                  <div
                    class="h-10 w-10 inline-flex items-center justify-center border border-default-300 text-default-800 rounded-lg transition-all group-hover:bg-primary group-hover:text-white group-hover:border-primary"
                  >
                    <InstagramIcon class="h-5 w-5" />
                  </div>
                  <h5 class="text-base font-medium text-default-800">Instagram</h5>
                </a>

                <a href="javascript:void(0);" class="flex items-center gap-5 group">
                  <div
                    class="h-10 w-10 inline-flex items-center justify-center border border-default-300 text-default-800 rounded-lg transition-all group-hover:bg-primary group-hover:text-white group-hover:border-primary"
                  >
                    <TwitterIcon class="h-5 w-5" />
                  </div>
                  <h5 class="text-base font-medium text-default-800">Twitter</h5>
                </a>

                <a href="javascript:void(0);" class="flex items-center gap-5 group">
                  <div
                    class="h-10 w-10 inline-flex items-center justify-center border border-default-300 text-default-800 rounded-lg transition-all group-hover:bg-primary group-hover:text-white group-hover:border-primary"
                  >
                    <LinkedinIcon class="h-5 w-5" />
                  </div>
                  <h5 class="text-base font-medium text-default-800">Linkedin</h5>
                </a>
              </div>
            </ul>
          </div>

          <div class="">
            <h5 class="xl:text-xl lg:text-lg font-medium text-default-800 mb-4">Legal & Press</h5>
            <ul class="flex flex-col gap-3">
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Privacy Policy</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Terms & Conditions</a
                >
              </li>
              <li>
                <a
                  href="javascript:void(0);"
                  class="text-base text-default-700 hover:text-default-950 transition-all"
                  >Presskit</a
                >
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="py-4">
      <div
        class="container flex flex-wrap justify-center items-center h-full md:justify-between text-center md:text-start"
      >
        <p class="text-base text-default-900">
          {{ year }}
          © AeroPage. Crafted and Coded with <span class="text-red-500">❤️</span> by
          <a class="text-primary-700" href="https://coderthemes.com/" target="_blank"
            >Coderthemes</a
          >
        </p>
        <p class="text-base">
          <a href="#">Terms Conditions & Policy</a>
        </p>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import logoDark from '@/assets/images/logo-dark.png'
import logoLight from '@/assets/images/logo-light.png'

import {
  MoveRightIcon,
  FacebookIcon,
  InstagramIcon,
  TwitterIcon,
  LinkedinIcon
} from 'lucide-vue-next'

const year = new Date().getFullYear()
</script>
