// FrameworkAngularReactTemplates/Aeropage_v1.1.0/Angular/Angular/src/app/landing/agency/services.component.ts
import { Component } from '@angular/core'
import { LucideAngularModule } from 'lucide-angular'

@Component({
  selector: 'app-services',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <!-- Start Services -->
    <section id="services" class="py-10 lg:py-20">
      <div class="container">
        <div class="mb-10 flex items-end justify-between">
          <div class="mx-auto max-w-2xl text-center">
            <span
              class="rounded-md border border-primary bg-primary/20 px-3 py-1 text-xs font-medium uppercase tracking-wider text-primary"
              >Services</span
            >
            <h2 class="my-4 text-4xl font-medium capitalize text-default-950">
              Our Services
            </h2>
            <p class="text-base">
              Lorem ipsum dummy text are usually use print and website industry.
            </p>
          </div>
        </div>
        <!-- flex End-->

        <div
          class="grid grid-cols-1 items-center divide-y divide-default-200 overflow-hidden rounded-md bg-default-100 dark:bg-default-50 lg:grid-cols-3 lg:divide-x lg:divide-y-0"
        >
          @for (item of agencyService; track $index) {
            <div class="group">
              <div class="p-8 sm:p-10">
                <span>
                  <lucide-angular
                    name="{{ item.icon }}"
                    class="size-14 text-default-950"
                  ></lucide-angular>
                </span>
                <h2 class="mb-4 mt-8 text-2xl font-medium text-default-950">
                  {{ item.title }}
                </h2>
                <p class="mb-6 text-base">
                  {{ item.content }}
                </p>
                <a href="javascript:void(0);" class="text-lg text-default-950"
                  >Read More
                  <lucide-angular
                    name="move-right"
                    class="inline-block size-6 opacity-0 transition-all duration-500 will-change-transform group-hover:translate-x-2 group-hover:opacity-100"
                  ></lucide-angular>
                </a>
              </div>
            </div>
          }
          <!-- end col -->
        </div>
        <!-- grid End-->
      </div>
      <!-- container End-->
    </section>
    <!-- End Services -->
  `,
  styles: ``,
})
export class ServicesComponent {
  agencyService = [
    {
      icon: 'component',
      title: 'Developer',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
    {
      icon: 'layers',
      title: 'Digital Product Design',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
    {
      icon: 'layout-grid',
      title: 'Branding & Design',
      content:
        'Lorem ipsum dummy text are usually used in these sections. Lorem ipsum dummy text is used in this design',
    },
  ]
}

// FrameworkAngularReactTemplates/Aeropage_v1.1.0/React/React/JS/src/pages/landing/Agency/components/Services.jsx
import { LuMoveRight } from "react-icons/lu";
import { services } from "../data";
import { Link } from "react-router-dom";

const Services = () => {
  return (
    <section id="services" className="lg:py-20 py-10">
      <div className="container">
        <div className="flex items-end justify-between mb-10">
          <div className="max-w-2xl mx-auto text-center">
            <span className="py-1 px-3 rounded-md text-xs font-medium uppercase tracking-wider border border-primary bg-primary/20 text-primary">
              Services
            </span>
            <h2 className="text-4xl font-medium capitalize text-default-950 my-4">
              Our Services
            </h2>
            <p className="text-base">
              Lorem ipsum dummy text are usually use print and website industry.
            </p>
          </div>
        </div>
        <div className="grid lg:grid-cols-3 grid-cols-1 items-center rounded-md overflow-hidden bg-default-100 dark:bg-default-50 divide-y lg:divide-y-0 lg:divide-x divide-default-200">
          {services.map((service, idx) => {
            const Icon = service.icon;
            return (
              <div key={idx} className="group">
                <div className="sm:p-10 p-8">
                  <span>
                    <Icon className="h-14 w-14 text-default-950" />
                  </span>
                  <h2 className="text-2xl text-default-950 font-medium mb-4 mt-8">
                    {service.title}
                  </h2>
                  <p className="text-base mb-6">{service.description}</p>
                  <Link to="" className="text-default-950 text-lg">
                    Read More
                    <LuMoveRight className="group-hover:opacity-100 opacity-0 w-6 h-6 inline-block transition-all duration-500 group-hover:translate-x-2 will-change-transform" />
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default Services;
